version: 3
includes:
  ui:
    taskfile: ../../frontend/Taskfile.yml
    dir: ../../frontend
    internal: true

tasks:

  web:
    aliases:
      - web-for-develop
    label: Run FwLiteWeb with Local LexBox, requires vite dev server to be running, use task fw-lite-web in root
    dir: ./FwLiteWeb
    cmd: dotnet watch --no-hot-reload

  tool-restore:
    cmd: dotnet tool restore
  add-migration:
    deps: [ tool-restore ]
    label: Add Migration
    desc: 'Usage: task add-migration "MigrationName"'
    dir: ./LcmCrdt
    cmd: dotnet ef migrations add {{.CLI_ARGS}}

  has-pending-model-changes:
    deps: [ tool-restore ]
    dir: ./LcmCrdt
    cmds:
      - dotnet ef migrations has-pending-model-changes

  maui-windows:
    label: Run Maui Windows, requires vite dev server to be running, use task fw-lite-win in root
    dir: ./FwLiteMaui
    cmd: dotnet run -f net9.0-windows10.0.19041.0

  publish-maui-windows:
    label: Publish Maui Windows
    dir: ./FwLiteMaui
    cmds:
      - dotnet publish -f net9.0-windows10.0.19041.0 --artifacts-path ../artifacts -p:WindowsPackageType=None
      - dotnet publish -f net9.0-windows10.0.19041.0 --artifacts-path ../artifacts

  build-maui-android:
    deps: [ ui:build-viewer-app ]
    label: Build Maui Android
    dir: ./FwLiteMaui
    cmd: dotnet build -f net9.0-android -t:InstallAndroidDependencies -p:AcceptAndroidSdkLicenses=True # "-p:AndroidSdkDirectory=D:\tools\android"

  publish-web-all:
    cmds:
      - task: publish-web-win
      - task: publish-web-linux
      - task: publish-web-osx
      - task: publish-web-osx-arm
  publish-web-win:
    dir: ./FwLiteWeb
    deps: [ ui:build-viewer-app ]
    cmd: dotnet publish -r win-x64
  publish-web-win-arm:
    dir: ./FwLiteWeb
    cmd: dotnet publish -r win-arm64
  publish-web-linux:
    dir: ./FwLiteWeb
    cmd: dotnet publish -r linux-x64
  publish-web-osx:
    dir: ./FwLiteWeb
    cmd: dotnet publish -r osx-x64
  publish-web-osx-arm:
    dir: ./FwLiteWeb
    cmd: dotnet publish -r osx-arm64
