version: 3
includes:
  ui:
    taskfile: ../../frontend/Taskfile.yml
    dir: ../../frontend
    internal: true

tasks:

  local-web-app-for-develop:
    label: dotnet
    dir: ./LocalWebApp
    cmd: dotnet watch --no-hot-reload
  local-web-app:
    label: Run LocalWebApp with Local LexBox
    env:
      Auth__DefaultAuthority: "https://localhost:3050"
    dir: ./LocalWebApp
    cmd: dotnet watch --no-hot-reload

  maui-desktop:
    deps: [ ui:build-viewer-app ]
    label: Run Maui Desktop
    dir: ./FwLiteDesktop
    cmd: dotnet run -f net9.0-windows10.0.19041.0

  publish-maui-desktop:
    label: Publish Maui Desktop
    dir: ./FwLiteDesktop
    cmds:
      - dotnet publish -f net9.0-windows10.0.19041.0 --artifacts-path ../artifacts -p:WindowsPackageType=None
      - dotnet publish -f net9.0-windows10.0.19041.0 --artifacts-path ../artifacts

  build-maui-android:
    deps: [ ui:build-viewer-app ]
    label: Build Maui Android
    dir: ./FwLiteDesktop
    cmd: dotnet build -f net9.0-android -t:InstallAndroidDependencies -p:AcceptAndroidSdkLicenses=True # "-p:AndroidSdkDirectory=D:\tools\android"

  publish-local-all:
    cmds:
      - task: publish-local-win
      - task: publish-local-linux
      - task: publish-local-osx
      - task: publish-local-osx-arm
  publish-local-win:
    dir: ./LocalWebApp
    deps: [ ui:build-viewer-app ]
    cmd: dotnet publish -r win-x64
  publish-local-win-arm:
    dir: ./LocalWebApp
    cmd: dotnet publish -r win-arm64
  publish-local-linux:
    dir: ./LocalWebApp
    cmd: dotnet publish -r linux-x64
  publish-local-osx:
    dir: ./LocalWebApp
    cmd: dotnet publish -r osx-x64
  publish-local-osx-arm:
    dir: ./LocalWebApp
    cmd: dotnet publish -r osx-arm64
