apiVersion: apps/v1
kind: Deployment
metadata:
  name: hg
  namespace: languagedepot
spec:
  template:
    spec:
      containers:
        - name: hgweb
          env:
            - name: APP_VERSION
              value: "dockerDev"

