# https://kubernetes.io/docs/concepts/configuration/secret

apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: languagedepot
stringData:
  POSTGRES_DB: 'lexbox'
  POSTGRES_PASSWORD: '972b722e63f549938d07bd8c4ee5086c'

---

apiVersion: v1
kind: Secret
metadata:
  name: hasura
  namespace: languagedepot
stringData:
  HASURA_GRAPHQL_ADMIN_SECRET: 'c67eeb626bee405d883b482046934860'

---

apiVersion: v1
kind: Secret
metadata:
  name: otel
  namespace: languagedepot
stringData:
  # Get test key at https://ui.honeycomb.io/sil-language-forge/environments/test/api_keys
  HONEYCOMB_API_KEY: '__REPLACE__'

---

apiVersion: v1
kind: Secret
metadata:
  name: ui
  namespace: languagedepot
stringData:
  PUBLIC_TURNSTILE_SITE_KEY: '1x0000000000000000000000000000000AA'

---

apiVersion: v1
kind: Secret
metadata:
  name: lexbox-api
  namespace: languagedepot
stringData:
  Authentication__Jwt__Secret: 'dev-secret_but-it-must-be-32-characters-long'
  CloudFlare__TurnstileKey: '1x0000000000000000000000000000000AA'

---

apiVersion: v1
kind: Secret
metadata:
  name: email
  namespace: languagedepot
stringData:
  SMTP_USER: 'maildev'
  SMTP_PASSWORD: 'maildev'

---

apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: languagedepot
stringData:
  deploy-key: ''
