apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

resources:
  - ../base
  - backup.yaml

patches:
  - path: lexbox-deployment.patch.yaml
  - path: app-config.yaml
  - path: hg-repos-volume.yaml
  - path: hg-deployment.yaml
  - path: ingress-config-prod.yaml
    target:
      kind: Ingress
      name: proxy
      namespace: languagedepot
