/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum DownloadProjectByCodeResult {
	Success = "Success",
	NotCrdtProject = "NotCrdtProject",
	ProjectNotFound = "ProjectNotFound",
	ProjectAlreadyDownloaded = "ProjectAlreadyDownloaded"
}
/* eslint-enable */
