/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IServerProjects} from './IServerProjects';
import type {IProjectModel} from './IProjectModel';
import type {DownloadProjectByCodeResult} from './DownloadProjectByCodeResult';
import type {ILexboxServer} from '../Auth/ILexboxServer';
import type {UserProjectRole} from '../../LcmCrdt/UserProjectRole';

export interface ICombinedProjectsService
{
	supportsFwData() : Promise<boolean>;
	remoteProjects() : Promise<IServerProjects[]>;
	serverProjects(serverId: string, forceRefresh: boolean) : Promise<IServerProjects>;
	localProjects() : Promise<IProjectModel[]>;
	downloadProjectByCode(code: string, server: ILexboxServer, userRole?: UserProjectRole) : Promise<DownloadProjectByCodeResult>;
	downloadProject(project: IProjectModel) : Promise<void>;
	createProject(name: string) : Promise<void>;
	deleteProject(code: string) : Promise<void>;
}
/* eslint-enable */
