/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IServerProjects} from './IServerProjects';
import type {IProjectModel} from './IProjectModel';
import type {ILexboxServer} from '../Auth/ILexboxServer';

export interface ICombinedProjectsService
{
	remoteProjects() : Promise<IServerProjects[]>;
	localProjects() : Promise<IProjectModel[]>;
	downloadProject(lexboxProjectId: string, projectName: string, server: ILexboxServer) : Promise<void>;
}
/* eslint-enable */
