/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IServerProjects} from './IServerProjects';
import type {IProjectModel} from './IProjectModel';
import type {ILexboxServer} from '../Auth/ILexboxServer';

export interface ICombinedProjectsService
{
	supportsFwData() : Promise<boolean>;
	remoteProjects() : Promise<IServerProjects[]>;
	serverProjects(serverId: string, forceRefresh: boolean) : Promise<IProjectModel[]>;
	localProjects() : Promise<IProjectModel[]>;
	downloadProject(projectId: string, server: ILexboxServer) : Promise<void>;
	createProject(name: string) : Promise<void>;
	deleteProject(projectId: string) : Promise<void>;
}
/* eslint-enable */
