/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ICrdtProject} from '../../LcmCrdt/ICrdtProject';

export interface IImportFwdataService
{
	import(projectName: string) : Promise<ICrdtProject>;
}
/* eslint-enable */
