/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IProjectIdentifier} from '../../MiniLcm/Models/IProjectIdentifier';

export interface IImportFwdataService
{
	import(projectName: string) : Promise<IProjectIdentifier>;
}
/* eslint-enable */
