/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IProjectModel
{
	name: string;
	crdt: boolean;
	fwdata: boolean;
	lexbox: boolean;
	serverAuthority?: string;
	id?: string;
}
/* eslint-enable */
