/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ILexboxServer} from '../Auth/ILexboxServer';

export interface IProjectModel
{
	name: string;
	code: string;
	crdt: boolean;
	fwdata: boolean;
	lexbox: boolean;
	role: number;
	server?: ILexboxServer;
	id?: string;
	apiEndpoint?: string;
}
/* eslint-enable */
