/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ILexboxServer} from '../Auth/ILexboxServer';
import type {IProjectModel} from './IProjectModel';

export interface IServerProjects
{
	server: ILexboxServer;
	projects: IProjectModel[];
	canDownloadByCode: boolean;
}
/* eslint-enable */
