/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IChange} from '../Changes/IChange';

export interface IChangeEntity
{
	index: number;
	commitId: string;
	entityId: string;
	change: IChange;
}
/* eslint-enable */
