/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ICommitMetadata
{
	authorName?: string;
	authorId?: string;
	clientVersion?: string;
	extraMetadata: { [key:string]: string };
	item?: string;
}
/* eslint-enable */
