"💻 FW Lite":
  - changed-files:
      - any-glob-to-any-file:
        - 'frontend/viewer/**'
      - all-globs-to-any-file:
        - 'backend/FwLite/**'
        - '!backend/FwLite/FwHeadless/**'

"📦 Lexbox":
  - changed-files:
      - any-glob-to-any-file:
        - 'backend/FwLite/FwHeadless/**'
        - 'hgweb/**'
        - 'deployment/**'
      - all-globs-to-any-file:
        - 'backend/**'
        - '!backend/FwLite/**'
        - '!backend/Directory.Packages.props'
      - all-globs-to-any-file:
        - 'frontend/**'
        - '!frontend/viewer/**'
        - '!frontend/pnpm-lock.yaml'
        - '!frontend/pnpm-workspace.yaml'

"📙 Platform.Bible extension":
  - changed-files:
      - any-glob-to-any-file:
        - 'platform.bible-extension/**'
