packages:
  - https-proxy
  - viewer

catalog:
  '@playwright/test': ^1.57.0
  '@stylistic/eslint-plugin': ^5.6.1
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@typescript-eslint/parser': ^8.48.0
  '@vitejs/plugin-basic-ssl': ^2.1.0
  '@vitest/browser': ^4.0.14
  '@vitest/ui': ^4.0.14
  autoprefixer: ^10.4.22
  eslint: ^9.39.1
  eslint-plugin-svelte: ^3.13.0
  playwright: ^1.54.0
  postcss: ^8.5.6
  runed: ^0.37.0
  svelte: ^5.45.2
  svelte-check: ^4.3.4
  svelte-eslint-parser: ^1.4.0
  svelte-exmarkdown: ^5.0.2
  svelte-preprocess: ^6.0.3
  tailwindcss: ^3.4.17
  tslib: ^2.8.1
  typescript: ^5.9.3
  typescript-eslint: ^8.48.0
  vite: ^7.2.6
  vitest: ^4.0.14

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - svelte-preprocess
