packages:
  - 'https-proxy'
  - 'viewer'

catalog:
  vite: ^6.0.3
  svelte: ~5.33.19
  svelte-check: ^4.1.4
  svelte-preprocess: ^6.0.3
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  postcss: ^8.4.49
  typescript: ^5.3.3
  tslib: ^2.6.2
  tailwindcss: ^3.4.17
  eslint: ^9.29.0
  vitest: ^3.2.3
  "@vitest/ui": ^3.2.3
  "@vitest/browser": ^3.2.3
  svelte-exmarkdown: ^4.0.3
  "@typescript-eslint/eslint-plugin": ^8.24.0
  "@typescript-eslint/parser": ^8.24.0
  "eslint-plugin-svelte": 2.46.1
  "svelte-eslint-parser": ^1.0.0-next.0
  "@stylistic/eslint-plugin": ^2.12.1
  "@vitejs/plugin-basic-ssl": ^1.2.0
  playwright: ^1.52.0
  "@playwright/test": ^1.52.0
  runed: ^0.27.0
