packages:
  - 'https-proxy'
  - 'viewer'

catalog:
  vite: ^5.4.11
  svelte: ^5.2.8
  svelte-check: ^4.1.0
  svelte-preprocess: ^6.0.3
  postcss: ^8.4.49
  typescript: ^5.3.3
  tslib: ^2.6.2
  tailwindcss: ^3.4.3
  eslint: ^9.15.0
  vitest: ^2.1.5
  "@vitest/ui": ^2.1.5
  "@typescript-eslint/eslint-plugin": "^8.16.0"
  "@typescript-eslint/parser": ^8.16.0
  "eslint-plugin-svelte": "^3.0.0-next.0"
  "svelte-eslint-parser": "^1.0.0-next.0"
  "@stylistic/eslint-plugin": "^2.11.0"
