packages:
  - https-proxy
  - viewer

catalog:
  vite: ^6.3.5
  svelte: ^5.36.14
  svelte-check: ^4.3.0
  svelte-preprocess: ^6.0.3
  '@sveltejs/vite-plugin-svelte': ^5.1.1
  postcss: ^8.5.6
  typescript: ^5.8.3
  tslib: ^2.8.1
  tailwindcss: ^3.4.17
  eslint: ^9.31.0
  vitest: ^3.2.4
  '@vitest/ui': ^3.2.4
  '@vitest/browser': ^3.2.4
  svelte-exmarkdown: ^4.0.3
  '@typescript-eslint/eslint-plugin': ^8.38.0
  '@typescript-eslint/parser': ^8.38.0
  typescript-eslint: ^8.38.0
  eslint-plugin-svelte: ^3.11.0
  svelte-eslint-parser: ^1.3.0
  '@stylistic/eslint-plugin': ^2.13.0
  '@vitejs/plugin-basic-ssl': ^1.2.0
  playwright: ^1.54.0
  '@playwright/test': ^1.54.0
  runed: ^0.27.0
