packages:
  - 'https-proxy'
  - 'viewer'

catalog:
  vite: ^5.4.9
  svelte: ^4.2.19
  svelte-check: ^3.7.1
  svelte-preprocess: ^5.1.4
  postcss: ^8.4.47
  typescript: ^5.3.3
  tslib: ^2.6.2
  tailwindcss: ^3.4.3
