packages:
  - 'https-proxy'
  - 'viewer'

catalog:
  vite: ^6.0.3
  svelte: ^5.12.0
  svelte-check: ^4.1.1
  svelte-preprocess: ^6.0.3
  "@sveltejs/vite-plugin-svelte": ^5.0.2
  postcss: ^8.4.49
  typescript: ^5.3.3
  tslib: ^2.6.2
  tailwindcss: ^3.4.3
  eslint: ^9.16.0
  vitest: ^2.1.8
  svelte-exmarkdown: ^4.0.2
  "@vitest/ui": ^2.1.8
  "@typescript-eslint/eslint-plugin": ^8.18.0
  "@typescript-eslint/parser": ^8.18.0
  "eslint-plugin-svelte": ^3.0.0-next.0
  "svelte-eslint-parser": ^1.0.0-next.0
  "@stylistic/eslint-plugin": ^2.12.1
  "@vitejs/plugin-basic-ssl": ^1.2.0
