version: 3
output: prefixed
includes:
  viewer:
    taskfile: ./viewer/Taskfile.yml
    dir: ./viewer
    internal: true
tasks:
  ui-only:
    aliases: [ o, only ]
    interactive: true
    deps: [ install ]
    cmd: pnpm run -r --parallel dev

  install:
    method: checksum
    sources:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    cmds:
      - corepack enable || true
      - pnpm install
  playwright-tests:
    aliases: [ pt ]
    cmd: pnpm run test {{.CLI_ARGS}}

  playwright-generate-tests:
    cmds:
      - pnpm dlx playwright codegen https://staging.languagedepot.org
  build:
    desc: "Builds the frontend app."
    aliases: [ b ]
    deps: [ install ]
    cmds:
      - pnpm run -r build
  check:
    desc: "Runs the frontend code checks done in CI. Note: the app must be built."
    aliases: [ sc, svelte-check ]
    deps: [ install ]
    ignore_error: true
    cmds:
      - pnpm run {{.CLI_ARGS}} --no-bail check
      - pnpm run {{.CLI_ARGS}} --no-bail lint

  svelte:
    desc: "Directory independent access to pnpm. E.g. `task svelte -- install`"
    aliases: [ s ]
    cmd: pnpm {{.CLI_ARGS}}

  build-viewer-app:
    deps: [viewer:build-app]
    label: vite
  viewer-dev:
    deps: [viewer:app]
    label: vite

  install-https-proxy:
    dir: ./https-proxy
    method: checksum
    sources:
      - package.json
    cmds:
      - corepack enable || true
      - pnpm install
  https-proxy:
    dir: ./https-proxy
    desc: "MSAL requires the oauth authority to be available over https. That's why this is here. As a bonus it dynamically looks for the UI either locally or in k8s."
    aliases: [ https-oauth-authority ]
    deps: [ install-https-proxy ]
    cmd: pnpm run dev

  check-out-of-date-translations:
    dir: ./src/lib/i18n
    silent: true
    cmd: node update_tracker.mjs

