version: 3
tasks:
  ui-only:
    aliases: [ o, only ]
    deps: [ install ]
    interactive: true
    cmds:
      - pnpm run dev

  install:
    method: checksum
    sources:
      - package.json
      - pnpm-lock.yaml
    cmds:
      - corepack enable || true
      - pnpm install

  playwright-generate-tests:
    cmds:
      - pnpm dlx playwright codegen https://staging.languagedepot.org
  build:
    desc: "Builds the frontend app."
    aliases: [ b ]
    deps: [ install ]
    cmds:
      - pnpm run build
  check:
    desc: "Runs the frontend code checks done in CI. Note: the app must be built."
    aliases: [ sc, svelte-check ]
    deps: [ install ]
    cmds:
      - pnpm run check
      - pnpm run lint

  svelte:
    desc: "Directory independent access to pnpm. E.g. `task svelte -- install`"
    aliases: [ s ]
    cmd: pnpm {{.CLI_ARGS}}
