/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export type ChangeType =
  | 'AddComplexFormTypeChange'
  | 'AddEntryComponentChange'
  | 'AddPublicationChange'
  | 'AddSemanticDomainChange'
  | 'AddTranslationChange'
  | 'CreateCommentThreadChange'
  | 'CreateComplexFormType'
  | 'CreateCustomViewChange'
  | 'CreateEntryChange'
  | 'CreateExampleSentenceChange'
  | 'CreateMorphTypeChange'
  | 'CreatePartOfSpeechChange'
  | 'CreatePublicationChange'
  | 'CreateSemanticDomainChange'
  | 'CreateSenseChange'
  | 'CreateSensePictureChange'
  | 'CreateUserCommentChange'
  | 'CreateWritingSystemChange'
  | 'EditCustomViewChange'
  | 'EditUserCommentChange'
  | 'MoveSenseToEntryChange'
  | 'RemoveComplexFormTypeChange'
  | 'RemovePublicationChange'
  | 'RemoveSemanticDomainChange'
  | 'RemoveSensePictureChange'
  | 'RemoveTranslationChange'
  | 'ReorderSensePictureChange'
  | 'ReplacePublicationChange'
  | 'ReplaceSemanticDomainChange'
  | 'SetCommentThreadStatusChange'
  | 'SetComplexFormComponentChange'
  | 'SetFirstTranslationIdChange'
  | 'SetMainPublicationChange'
  | 'SetOrderChange:ComplexFormComponent'
  | 'SetOrderChange:ExampleSentence'
  | 'SetOrderChange:Sense'
  | 'SetOrderChange:WritingSystem'
  | 'SetPartOfSpeechChange'
  | 'UpdateSensePictureChange'
  | 'UpdateTranslationChange'
  | 'create:pendingUpload'
  | 'create:remote-resource'
  | 'delete:CommentThread'
  | 'delete:ComplexFormComponent'
  | 'delete:ComplexFormType'
  | 'delete:CustomView'
  | 'delete:Entry'
  | 'delete:ExampleSentence'
  | 'delete:PartOfSpeech'
  | 'delete:Publication'
  | 'delete:RemoteResource'
  | 'delete:SemanticDomain'
  | 'delete:Sense'
  | 'delete:UserComment'
  | 'delete:WritingSystem'
  | 'jsonPatch:ComplexFormType'
  | 'jsonPatch:Entry'
  | 'jsonPatch:ExampleSentence'
  | 'jsonPatch:MorphType'
  | 'jsonPatch:PartOfSpeech'
  | 'jsonPatch:Publication'
  | 'jsonPatch:SemanticDomain'
  | 'jsonPatch:Sense'
  | 'jsonPatch:WritingSystem'
  | 'uploaded:RemoteResource';

export const knownChangeTypes = [
  'AddComplexFormTypeChange',
  'AddEntryComponentChange',
  'AddPublicationChange',
  'AddSemanticDomainChange',
  'AddTranslationChange',
  'CreateCommentThreadChange',
  'CreateComplexFormType',
  'CreateCustomViewChange',
  'CreateEntryChange',
  'CreateExampleSentenceChange',
  'CreateMorphTypeChange',
  'CreatePartOfSpeechChange',
  'CreatePublicationChange',
  'CreateSemanticDomainChange',
  'CreateSenseChange',
  'CreateSensePictureChange',
  'CreateUserCommentChange',
  'CreateWritingSystemChange',
  'EditCustomViewChange',
  'EditUserCommentChange',
  'MoveSenseToEntryChange',
  'RemoveComplexFormTypeChange',
  'RemovePublicationChange',
  'RemoveSemanticDomainChange',
  'RemoveSensePictureChange',
  'RemoveTranslationChange',
  'ReorderSensePictureChange',
  'ReplacePublicationChange',
  'ReplaceSemanticDomainChange',
  'SetCommentThreadStatusChange',
  'SetComplexFormComponentChange',
  'SetFirstTranslationIdChange',
  'SetMainPublicationChange',
  'SetOrderChange:ComplexFormComponent',
  'SetOrderChange:ExampleSentence',
  'SetOrderChange:Sense',
  'SetOrderChange:WritingSystem',
  'SetPartOfSpeechChange',
  'UpdateSensePictureChange',
  'UpdateTranslationChange',
  'create:pendingUpload',
  'create:remote-resource',
  'delete:CommentThread',
  'delete:ComplexFormComponent',
  'delete:ComplexFormType',
  'delete:CustomView',
  'delete:Entry',
  'delete:ExampleSentence',
  'delete:PartOfSpeech',
  'delete:Publication',
  'delete:RemoteResource',
  'delete:SemanticDomain',
  'delete:Sense',
  'delete:UserComment',
  'delete:WritingSystem',
  'jsonPatch:ComplexFormType',
  'jsonPatch:Entry',
  'jsonPatch:ExampleSentence',
  'jsonPatch:MorphType',
  'jsonPatch:PartOfSpeech',
  'jsonPatch:Publication',
  'jsonPatch:SemanticDomain',
  'jsonPatch:Sense',
  'jsonPatch:WritingSystem',
  'uploaded:RemoteResource',
] as const satisfies readonly ChangeType[];

/* eslint-enable */
