/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ChangeType} from './ChangeType';
import type {ActivitySort} from './ActivitySort';

export interface IActivityQuery
{
	authorFilterKeys?: string[];
	changeTypeKeys?: ChangeType[];
	sort: ActivitySort;
}
/* eslint-enable */
