/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IChangeEntity} from '../SIL/Harmony/Core/IChangeEntity';
import type {IActivityChangeInfo} from './IActivityChangeInfo';

export interface IActivityChange
{
	entity: IChangeEntity;
	info: IActivityChangeInfo;
}
/* eslint-enable */
