/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from '../MiniLcm/Models/IObjectWithId';
import type {IEntry} from '../MiniLcm/Models/IEntry';

export interface IChangeContext
{
	commitId: string;
	changeIndex: number;
	changeName: string;
	snapshot?: IObjectWithId;
	affectedEntries: IEntry[];
	entityType: string;
}
/* eslint-enable */
