/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IProjectIdentifier} from '../MiniLcm/Models/IProjectIdentifier';
import type {ProjectDataFormat} from '../MiniLcm/Models/ProjectDataFormat';
import type {IProjectData} from './IProjectData';

export interface ICrdtProject extends IProjectIdentifier
{
	name: string;
	dataFormat: ProjectDataFormat;
	dbPath: string;
	data?: IProjectData;
}
/* eslint-enable */
