/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from '../MiniLcm/Models/IObjectWithId';

export interface IHistoryLineItem
{
	commitId: string;
	entityId: string;
	timestamp: string;
	snapshotId?: string;
	changeName?: string;
	entity?: IObjectWithId;
	entityName?: string;
}
/* eslint-enable */
