/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IProjectData
{
	name: string;
	code: string;
	id: string;
	originDomain?: string;
	clientId: string;
	fwProjectId?: string;
	lastUserName?: string;
	lastUserId?: string;
	serverId?: string;
}
/* eslint-enable */
