files:
  - source: /frontend/viewer/src/locales/en.po
    translation: /frontend/viewer/src/locales/%two_letters_code%.po
  - source: /frontend/src/lib/i18n/locales/en.json
    translation: /frontend/src/lib/i18n/locales/%two_letters_code%.json
  - source: /platform.bible-extension/assets/descriptions/description-en.md
    translation: /platform.bible-extension/assets/descriptions/description-%two_letters_code%.md
