files:
  - source: /frontend/viewer/src/locales/en.json
    translation: /frontend/viewer/src/locales/%two_letters_code%.json
  - source: /frontend/src/lib/i18n/locales/en.json
    translation: /frontend/src/lib/i18n/locales/%two_letters_code%.json
