files:
  - source: frontend/viewer/src/locales/en.po
    translation: frontend/viewer/src/locales/%two_letters_code%.po
  - source: '**/descriptions/description-en.md'
    translation: '**/descriptions/description-%two_letters_code%.md'
