schema:
  - ./frontend/schema.graphql
  - ./schema-extensions.graphql
include:
  - '**/*.ts'
  - '**/*.graphql'
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8080/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
