apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: lexbox
build:
  artifacts:
    - image: ghcr.io/sillsdev/hgresume
      context: hgresumable
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/sillsdev/lexbox-api
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**"
            dest: /src/backend
    - image: ghcr.io/sillsdev/lexbox-hasura
      context: hasura
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/sillsdev/lexbox-hgweb
      context: hgweb
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/sillsdev/lexbox-ui
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**"
            dest: /app
portForward:
  # Backend
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 80
    localPort: 5158
  # OpenTelemetry
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 4318
  # Svelte-Kit frontend
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 3000
manifests:
  kustomize:
    paths:
      - .
  hooks:
    before:
      - host:
          command: ["sh", "-c", "kubectl apply -f deployment/db-deployment.yaml"]
          os: [darwin, linux]
      - host:
          command: ["powershell", "-Command", "kubectl apply -f deployment/db-deployment.yaml"]
          os: [windows]

profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: LexBoxApi/dev.Dockerfile
      - op: replace
        path: /build/artifacts/4/docker/dockerfile
        value: dev.Dockerfile
