apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: lexbox
deploy:
  kubeContext: docker-desktop
build:
  artifacts:
    - image: ghcr.io/sillsdev/lexbox-api
      context: backend
      docker:
        dockerfile: LexBoxApi/dev.Dockerfile
      sync:
        manual:
          - src: '**'
            dest: /src/backend
    - image: ghcr.io/sillsdev/lexbox-ui
      context: frontend
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: '**'
            dest: /app
    - image: ghcr.io/sillsdev/hgresume
      context: hgresumable
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/sillsdev/lexbox-hgweb
      context: hgweb
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
    concurrency: 2
portForward:
  # Backend
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 5158
  # OpenTelemetry
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 4318
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 18888
  # Svelte-Kit frontend
  - resourceType: Service
    resourceName: ui
    namespace: languagedepot
    port: 3000
  - resourceType: Service
    resourceName: db
    namespace: languagedepot
    port: 5432
    localPort: 5433
#    maildev
  - resourceType: Service
    resourceName: lexbox
    namespace: languagedepot
    port: 1080
    # hg
  - resourceType: Service
    resourceName: hg
    namespace: languagedepot
    port: 8088 # web

manifests:
  kustomize:
    paths:
      - deployment/local-dev

profiles:
  - name: dev
    activation:
      - command: dev
  - name: infra
    portForward:
      # Postgres
      - resourceType: Service
        resourceName: db
        namespace: languagedepot
        port: 5432
        localPort: 5433
      # OpenTelemetry
      - resourceType: Service
        resourceName: lexbox
        namespace: languagedepot
        port: 4318 # http
      - resourceType: Service
        resourceName: lexbox
        namespace: languagedepot
        port: 4317 # grpc
      - resourceType: Service
        resourceName: lexbox
        namespace: languagedepot
        port: 18888
      # hg
      - resourceType: Service
        resourceName: hg
        namespace: languagedepot
        port: 8088 # web
      - resourceType: Service
        resourceName: hg
        namespace: languagedepot
        port: 80 # resumable
        localPort: 8034
      #    maildev
      - resourceType: Service
        resourceName: lexbox
        namespace: languagedepot
        port: 1080
      - resourceType: Service
        resourceName: lexbox
        namespace: languagedepot
        port: 1025

  - name: no-frontend
    portForward:
    # Postgres - for dev convenience
    - resourceType: Service
      resourceName: db
      namespace: languagedepot
      port: 5432
      localPort: 5433
    # Backend
    - resourceType: Service
      resourceName: lexbox
      namespace: languagedepot
      port: 5158
    # OpenTelemetry
    - resourceType: Service
      resourceName: lexbox
      namespace: languagedepot
      port: 4318
    - resourceType: Service
      resourceName: lexbox
      namespace: languagedepot
      port: 18888
  #    maildev
    - resourceType: Service
      resourceName: lexbox
      namespace: languagedepot
      port: 1080
