# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: '3'
vars:
  TESTING_DIR: './backend/Testing'
  HG_REPO_DIR: './hgweb/repos'
includes:
  k8s:
    taskfile: ./deployment/Taskfile.yml
    dir: ./deployment

tasks:
  setup:
    deps: [ setup-win, setup-unix ]
    cmds:
      - git config blame.ignoreRevsFile .git-blame-ignore-revs
  setup-win:
    platforms: [ windows ]
    cmds:
      - cmd: powershell rm -r {{.HG_REPO_DIR}}/sena-3
        ignore_error: true
        silent: true
      - powershell -Command "Invoke-WebRequest 'https://drive.google.com/uc?export=download&id=1I-hwc0RHoQqW774gbS5qR-GHa1E7BlsS' -OutFile sena-3.zip"
      - powershell -Command "Expand-Archive sena-3.zip -DestinationPath {{.HG_REPO_DIR}}"
      - powershell rm sena-3.zip
  setup-unix:
    platforms: [ linux, darwin ]
    cmds:
      - cmd: rm -rf {{.HG_REPO_DIR}}/sena-3
        ignore_error: true
        silent: true
      - wget -O sena-3.zip 'https://drive.google.com/uc?export=download&id=1I-hwc0RHoQqW774gbS5qR-GHa1E7BlsS'
      - unzip -q sena-3.zip -d {{.HG_REPO_DIR}}/
      - rm sena-3.zip

  # docker
  up:
    cmds:
      - docker compose up --wait
  down:
    cmds:
      - docker compose down

  # tests
  test:
    dir: '{{.TESTING_DIR}}'
    cmds:
      - dotnet test
  test-sr:
    dir: '{{.TESTING_DIR}}'
    deps: [ up ]
    cmds:
      - dotnet test --filter=SendReceive

  # dev
  infra-up: # infrastructure for our ui and api
    vars:
      WAIT: '{{default true .WAIT}}'
    cmds:
      - docker compose up maildev db hasura hgweb otel-collector hgresumable -d --wait={{.WAIT}}

  dev:
    deps: [ ui, api ]

  # ui
  ui:
    dir: ./frontend
    deps: [ infra-up, ui-down, ui-install ]
    interactive: true
    cmds:
      - pnpm run dev
  ui-install:
    dir: ./frontend
    method: checksum
    sources:
      - package.json
      - pnpm-lock.yaml
    cmds:
      - corepack enable
      - pnpm install
  ui-down:
    cmds:
      - docker compose stop ui

  # api
  api:
    dir: ./backend/LexBoxApi
    deps: [ infra-up, api-down ]
    interactive: true
    cmds:
      - dotnet watch
  api-down:
    cmds:
      - docker compose stop lexbox-api
