/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ILcmFileMetadata} from './ILcmFileMetadata';

export interface IMediaFile
{
	uri: string;
	metadata: ILcmFileMetadata;
}
/* eslint-enable */
