/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {UploadFileResult} from './UploadFileResult';

export interface IUploadFileResponse
{
	result: UploadFileResult;
	errorMessage?: string;
	mediaUri?: string;
}
/* eslint-enable */
