/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum ReadFileResult {
	Success = "Success",
	NotFound = "NotFound",
	Offline = "Offline",
	NotSupported = "NotSupported",
	Error = "Error"
}
/* eslint-enable */
