/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum UploadFileResult {
	SavedLocally = "SavedLocally",
	SavedToLexbox = "SavedToLexbox",
	TooBig = "TooBig",
	NotSupported = "NotSupported",
	AlreadyExists = "AlreadyExists",
	Error = "Error"
}
/* eslint-enable */
