# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: '3'

tasks:
  crowdin:
    dotenv: [.crowdin-env.local]
    cmd: crowdin {{.CLI_ARGS}} -b develop

  pull:
    cmd: task crowdin -- pull

  dryrun:
    desc: Dry run push sources and push translations for a single language (defaulting to Swahili)
    vars:
      LOCALE: '{{.LOCALE | default "sw"}}'
    cmds:
      - task crowdin -- push sources --dryrun
      - task crowdin -- push translations -l {{.LOCALE}} --dryrun

  i18n:
    dir: ../frontend/viewer
    cmds:
      - task i18n

  push-sources:
    desc: Push English source strings to Crowdin
    cmd: task crowdin -- push sources

  push-translations-non-mt:
    desc: Push translations for non-MT languages (ms, sw)
    cmds:
      - task crowdin -- push translations -l ms
      - task crowdin -- push translations -l sw
