/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';

export interface IComplexFormComponent extends IObjectWithId
{
	deletedAt?: string;
	complexFormEntryId: string;
	complexFormHeadword?: string;
	componentEntryId: string;
	componentSenseId?: string;
	componentHeadword?: string;
}
/* eslint-enable */
