/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {SubjectType} from './SubjectType';
import type {ThreadStatus} from './ThreadStatus';
import type {IUserComment} from './IUserComment';

export interface ICommentThread extends IObjectWithId
{
	id: string;
	deletedAt?: string;
	subjectId: string;
	subjectType: SubjectType;
	status: ThreadStatus;
	createdAt: string;
	updatedAt: string;
	comments?: IUserComment[];
}
/* eslint-enable */
