/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {ViewBase} from './ViewBase';
import type {IViewField} from './IViewField';

export interface ICustomView extends IObjectWithId
{
	id: string;
	deletedAt?: string;
	name: string;
	base: ViewBase;
	entryFields: IViewField[];
	senseFields: IViewField[];
	exampleFields: IViewField[];
	vernacular?: string[];
	analysis?: string[];
}
/* eslint-enable */
