/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IMultiString} from '$lib/dotnet-types/i-multi-string';
import type {ISense} from './ISense';
import type {IComplexFormComponent} from './IComplexFormComponent';
import type {IComplexFormType} from './IComplexFormType';

export interface IEntry
{
	id: string;
	deletedAt?: string;
	lexemeForm: IMultiString;
	citationForm: IMultiString;
	literalMeaning: IMultiString;
	senses: ISense[];
	note: IMultiString;
	components: IComplexFormComponent[];
	complexForms: IComplexFormComponent[];
	complexFormTypes: IComplexFormType[];
}
/* eslint-enable */
