/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {IMultiString} from '$lib/dotnet-types/i-multi-string';
import type {IRichMultiString} from '$lib/dotnet-types/i-multi-string';
import type {MorphType} from './MorphType';
import type {ISense} from './ISense';
import type {IComplexFormComponent} from './IComplexFormComponent';
import type {IComplexFormType} from './IComplexFormType';
import type {IPublication} from './IPublication';

export interface IEntry extends IObjectWithId
{
	id: string;
	deletedAt?: string;
	lexemeForm: IMultiString;
	citationForm: IMultiString;
	literalMeaning: IRichMultiString;
	morphType: MorphType;
	senses: ISense[];
	note: IRichMultiString;
	components: IComplexFormComponent[];
	complexForms: IComplexFormComponent[];
	complexFormTypes: IComplexFormType[];
	publishIn: IPublication[];
}
/* eslint-enable */
