/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IEntry} from './IEntry';

export interface IEntriesWindow
{
	entries: IEntry[];
	totalCount: number;
	offset: number;
	targetIndex?: number;
}
/* eslint-enable */
