/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {IRichMultiString} from '$lib/dotnet-types/i-multi-string';
import type {ITranslation} from './ITranslation';
import type {IRichString} from './IRichString';

export interface IExampleSentence extends IObjectWithId
{
	id: string;
	sentence: IRichMultiString;
	translations: ITranslation[];
	reference?: IRichString;
	senseId: string;
	deletedAt?: string;
}
/* eslint-enable */
