/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IMultiString} from '$lib/dotnet-types/i-multi-string';

export interface IExampleSentence
{
	id: string;
	sentence: IMultiString;
	translation: IMultiString;
	reference?: string;
	senseId: string;
	deletedAt?: string;
}
/* eslint-enable */
