/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {MorphType} from './MorphType';
import type {IMultiString} from '$lib/dotnet-types/i-multi-string';
import type {IRichMultiString} from '$lib/dotnet-types/i-multi-string';

export interface IMorphTypeData extends IObjectWithId
{
	id: string;
	morphType: MorphType;
	name: IMultiString;
	abbreviation: IMultiString;
	description: IRichMultiString;
	leadingToken?: string;
	trailingToken?: string;
	secondaryOrder: number;
	deletedAt?: string;
}
/* eslint-enable */
