/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {IMultiString} from '$lib/dotnet-types/i-multi-string';

export interface IPartOfSpeech extends IObjectWithId
{
	id: string;
	name: IMultiString;
	deletedAt?: string;
	predefined: boolean;
}
/* eslint-enable */
