/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';

export interface IPlugin extends IObjectWithId
{
	id: string;
	deletedAt?: string;
	name: string;
	description?: string;
	fileUri: string;
	fileSize: number;
	permissions: string[];
	contexts: string[];
	requires: string[];
}
/* eslint-enable */
