/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ProjectDataFormat} from './ProjectDataFormat';

export interface IProjectIdentifier
{
	name: string;
	dataFormat: ProjectDataFormat;
}
/* eslint-enable */
