/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {RichTextToggle} from './RichTextToggle';
import type {RichTextAlign} from './RichTextAlign';
import type {RichTextSuperscript} from './RichTextSuperscript';
import type {RichTextUnderline} from './RichTextUnderline';
import type {RichTextSizeUnit} from './RichTextSizeUnit';
import type {RichTextSpellingMode} from './RichTextSpellingMode';
import type {RichTextEditable} from './RichTextEditable';
import type {IRichTextObjectData} from './IRichTextObjectData';

export interface IRichSpan
{
	ws: string;
	wsBase?: string;
	italic?: RichTextToggle;
	bold?: RichTextToggle;
	align?: RichTextAlign;
	superscript?: RichTextSuperscript;
	underline?: RichTextUnderline;
	fontFamily?: string;
	fontSize?: number;
	fontSizeUnit?: RichTextSizeUnit;
	fontVariations?: string;
	offset?: number;
	offsetUnit?: RichTextSizeUnit;
	foreColor?: string;
	backColor?: string;
	underColor?: string;
	firstIndent?: number;
	leadingIndent?: number;
	trailingIndent?: number;
	spaceBefore?: number;
	spaceAfter?: number;
	marginTop?: number;
	tabDef?: number;
	lineHeight?: number;
	lineHeightUnit?: RichTextSizeUnit;
	paraColor?: string;
	spellCheck?: RichTextSpellingMode;
	rightToLeft?: number;
	directionDepth?: number;
	keepWithNext?: number;
	keepTogether?: number;
	hyphenate?: number;
	maxLines?: number;
	cellBorderWidth?: number;
	cellSpacing?: number;
	cellPadding?: number;
	editable?: RichTextEditable;
	setRowDefaults?: number;
	relLineHeight?: number;
	widowOrphan?: number;
	padTop?: number;
	padBottom?: number;
	padLeading?: number;
	padTrailing?: number;
	paraStyle?: string;
	charStyle?: string;
	namedStyle?: string;
	wsStyle?: string;
	borderTop?: number;
	borderBottom?: number;
	borderLeading?: number;
	borderTrailing?: number;
	borderColor?: string;
	bulNumScheme?: number;
	bulNumStartAt?: number;
	bulNumTxtBef?: string;
	bulNumTxtAft?: string;
	bulNumFontInfo?: string;
	customBullet?: string;
	tabList?: string;
	tableRule?: number;
	fieldName?: string;
	objData?: IRichTextObjectData;
	tags?: string[];
	text: string;
}
/* eslint-enable */
