/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {RichTextObjectDataType} from './RichTextObjectDataType';

export interface IRichTextObjectData
{
	value: string;
	type: RichTextObjectDataType;
	isGuidType: boolean;
}
/* eslint-enable */
