/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IMultiString} from '$lib/dotnet-types/i-multi-string';

export interface ISemanticDomain
{
	id: string;
	name: IMultiString;
	code: string;
	deletedAt?: string;
	predefined: boolean;
}
/* eslint-enable */
