/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';

export interface IUserComment extends IObjectWithId
{
	id: string;
	deletedAt?: string;
	commentThreadId: string;
	previousCommentId?: string;
	text: string;
	authorId?: string;
	authorName?: string;
	createdAt: string;
	updatedAt: string;
}
/* eslint-enable */
