/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from './IObjectWithId';
import type {IVariantType} from './IVariantType';
import type {IRichMultiString} from '$lib/dotnet-types/i-multi-string';

export interface IVariant extends IObjectWithId
{
	deletedAt?: string;
	variantEntryId: string;
	variantHeadword?: string;
	mainEntryId: string;
	mainSenseId?: string;
	mainHeadword?: string;
	types: IVariantType[];
	hideMinorEntry: boolean;
	comment: IRichMultiString;
}
/* eslint-enable */
