/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IWritingSystem} from './IWritingSystem';

export interface IWritingSystems
{
	analysis: IWritingSystem[];
	vernacular: IWritingSystem[];
}
/* eslint-enable */
