/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {WritingSystemType} from './WritingSystemType';

export interface IWritingSystem
{
	id: string;
	wsId: string;
	name: string;
	abbreviation: string;
	font: string;
	deletedAt?: string;
	type: WritingSystemType;
	exemplars: string[];
	order: number;
}
/* eslint-enable */
