/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum MorphType {
	Unknown = "Unknown",
	BoundRoot = "BoundRoot",
	BoundStem = "BoundStem",
	Circumfix = "Circumfix",
	Clitic = "Clitic",
	Enclitic = "Enclitic",
	Infix = "Infix",
	Particle = "Particle",
	Prefix = "Prefix",
	Proclitic = "Proclitic",
	Root = "Root",
	Simulfix = "Simulfix",
	Stem = "Stem",
	Suffix = "Suffix",
	Suprafix = "Suprafix",
	InfixingInterfix = "InfixingInterfix",
	PrefixingInterfix = "PrefixingInterfix",
	SuffixingInterfix = "SuffixingInterfix",
	Phrase = "Phrase",
	DiscontiguousPhrase = "DiscontiguousPhrase",
	Other = "Other"
}
/* eslint-enable */
