/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RichTextSuperscript {
	None = 0,
	Superscript = 1,
	Subscript = 2
}
/* eslint-enable */
