/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RichTextUnderline {
	None = 0,
	Dotted = 1,
	Dashed = 2,
	Strikethrough = 3,
	Single = 4,
	Double = 5,
	Squiggle = 6
}
/* eslint-enable */
