/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RichTextEditable {
	NotEditable = 0,
	IsEditable = 1,
	SemiEditable = 2
}
/* eslint-enable */
