/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RichTextAlign {
	Leading = 0,
	Left = 1,
	Center = 2,
	Right = 3,
	Trailing = 4,
	Justify = 5
}
/* eslint-enable */
