/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RichTextSpellingMode {
	Normal = 0,
	DoNotCheck = 1,
	ForceCheck = 2
}
/* eslint-enable */
