/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum RichTextObjectDataType {
	Unknown = 0,
	PictureEven = 1,
	PictureOdd = 2,
	NameGuid = 3,
	ExternalPathName = 4,
	OwnNameGuid = 5,
	EmbeddedObjectData = 6,
	ContextString = 7,
	GuidMoveableObjDisp = 8
}
/* eslint-enable */
