/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum WritingSystemType {
	Vernacular = 0,
	Analysis = 1
}
/* eslint-enable */
