apiVersion: v1
kind: Pod
metadata:
  name: kopia-maint
spec:
  containers:
  - name: kopia
    image: kopia/kopia:latest
    command: [ "/bin/bash" ]
    args: [ "-c", "trap : TERM INT; sleep infinity & wait" ]
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    env:
    - name: GOMEMLIMIT
      value: 900MiB
    - name: KOPIA_PASSWORD
      valueFrom:
        secretKeyRef:
          key: KOPIA_PASSWORD
          name: backups
    volumeMounts:
    - mountPath: /app/config/repository.config
      name: config
      subPath: repository.config
    - mountPath: /dump
      name: pg-dump
    - mountPath: /hg-repos
      name: hg-repos
  - name: pg
    image: postgres:15-alpine
    command: [ "/bin/bash" ]
    args: [ "-c", "trap : TERM INT; sleep infinity & wait" ]
    resources:
      limits:
        memory: 150Mi
      requests:
        memory: 150Mi
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: POSTGRES_PASSWORD
          name: db
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: POSTGRES_DB
          name: db
    volumeMounts:
    - mountPath: /dump
      name: pg-dump
  restartPolicy: Never
  volumes:
  - name: config
    secret:
      items:
      - key: kopia.config
        path: repository.config
      secretName: backups
  - emptyDir:
      sizeLimit: 1Gi
    name: pg-dump
  - name: hg-repos
    persistentVolumeClaim:
      claimName: hg-repos