/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IObjectSnapshot
{
	id: string;
	typeName: string;
	entity: unknown;
	references: string[];
	entityId: string;
	entityIsDeleted: boolean;
	commitId: string;
	commit: unknown;
	isRoot: boolean;
}
/* eslint-enable */
