#!/bin/bash

# cwd while running script is inside hg repo, so ensure we look for ChorusMerge.dll in right place
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

exec dotnet "${SCRIPT_DIR}/ChorusMerge.dll" "$@"
