/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ProjectSyncStatusEnum} from './ProjectSyncStatusEnum';

export interface IProjectSyncStatus
{
	status: ProjectSyncStatusEnum;
	pendingCrdtChanges: number;
	pendingMercurialChanges: number;
	lastCrdtCommitDate?: string;
	lastMercurialCommitDate?: string;
}
/* eslint-enable */
