/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IProjectSyncStatus
{
	status: number;
	pendingCrdtChanges: number;
	pendingMercurialChanges: number;
	lastCrdtCommitDate?: string;
	lastMercurialCommitDate?: string;
	neverSynced: IProjectSyncStatus;
	syncing: IProjectSyncStatus;
	queuedToSync: IProjectSyncStatus;
}
/* eslint-enable */
