/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {SyncJobResultEnum} from './SyncJobResultEnum';
import type {ISyncResult} from './ISyncResult';

export interface ISyncJobResult
{
	result: SyncJobResultEnum;
	error?: string;
	syncResult?: ISyncResult;
}
/* eslint-enable */
