/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum SyncJobStatusEnum {
	Success = "Success",
	SuccessHarmonyOnly = "SuccessHarmonyOnly",
	ProjectNotFound = "ProjectNotFound",
	SyncJobNotFound = "SyncJobNotFound",
	SyncJobTimedOut = "SyncJobTimedOut",
	TimedOutAwaitingSyncStatus = "TimedOutAwaitingSyncStatus",
	UnableToAuthenticate = "UnableToAuthenticate",
	UnableToSync = "UnableToSync",
	CrdtSyncFailed = "CrdtSyncFailed",
	SendReceiveFailed = "SendReceiveFailed",
	SyncBlocked = "SyncBlocked",
	UnknownError = "UnknownError"
}
/* eslint-enable */
