/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum SyncJobResultEnum {
	Success = "Success",
	ProjectNotFound = "ProjectNotFound",
	SyncJobNotFound = "SyncJobNotFound",
	SyncJobTimedOut = "SyncJobTimedOut",
	UnableToAuthenticate = "UnableToAuthenticate",
	UnableToSync = "UnableToSync",
	CrdtSyncFailed = "CrdtSyncFailed",
	SendReceiveFailed = "SendReceiveFailed",
	UnknownError = "UnknownError"
}
/* eslint-enable */
