/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */


import type {IEntry, IMiniLcmJsInvokable} from '$lib/dotnet-types';

export type ILexboxApiHub = IMiniLcmJsInvokable;

export type ILexboxClient = {
    /**
    * @param entry Transpiled from lexboxClientContracts.Entry
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    OnEntryUpdated(entry: IEntry): Promise<void>;
    OnProjectClosed(reason: CloseReason): Promise<void>;
}

export enum CloseReason {
    User = 0,
    Locked = 1,
}
