/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */

import type { Entry } from '../../mini-lcm';
import type {LexboxApi} from '../../services/lexbox-api';

export type ILexboxApiHub = LexboxApi;

export type ILexboxClient = {
    /**
    * @param entry Transpiled from lexboxClientContracts.Entry
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    OnEntryUpdated(entry: Entry): Promise<void>;
    OnProjectClosed(reason: CloseReason): Promise<void>;
}

export enum CloseReason {
    User = 0,
    Locked = 1,
}
