using System.Text.RegularExpressions;
using Microsoft.Data.Sqlite;

namespace LcmCrdt.Project;

/// <summary>
/// Applies a Guid-scrubbed SQL project template (see issue #1920) to a fresh sqlite
/// file, replacing each placeholder token with a freshly-generated Guid so every
/// resulting database has unique commit Ids, ClientIds, etc.
///
/// Templates are generated by dumping a CRDT sqlite project and passing the result
/// through Verify's inline-Guid scrubber, which emits <c>Guid_1</c>, <c>Guid_2</c>, …
/// tokens — same number for repeated occurrences of the same Guid.
/// </summary>
public static class ProjectTemplate
{
    public static void Apply(string templateSql, string targetSqlitePath)
    {
        if (File.Exists(targetSqlitePath)) File.Delete(targetSqlitePath);
        var resolvedSql = HydrateGuids(templateSql);

        using var conn = new SqliteConnection($"Data Source={targetSqlitePath}");
        conn.Open();
        using var cmd = conn.CreateCommand();
        cmd.CommandText = resolvedSql;
        cmd.ExecuteNonQuery();
    }

    private static readonly Regex TokenRegex = new(@"\bGuid_(\d+)\b", RegexOptions.Compiled);

    private static string HydrateGuids(string templateSql)
    {
        var assignments = new Dictionary<int, Guid>();
        foreach (Match m in TokenRegex.Matches(templateSql))
            assignments.TryAdd(int.Parse(m.Groups[1].Value), Guid.NewGuid());

        return TokenRegex.Replace(templateSql, m =>
            assignments[int.Parse(m.Groups[1].Value)].ToString().ToUpperInvariant());
    }
}
