/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IServerStatus} from './IServerStatus';
import type {LoginResult} from './LoginResult';
import type {ILexboxServer} from './ILexboxServer';

export interface IAuthService
{
	servers() : Promise<IServerStatus[]>;
	signInWebView(server: ILexboxServer) : Promise<LoginResult>;
	useSystemWebView() : Promise<boolean>;
	logout(server: ILexboxServer) : Promise<void>;
}
/* eslint-enable */
