/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ILexboxServer} from './ILexboxServer';

export interface IServerStatus
{
	displayName: string;
	loggedIn: boolean;
	loggedInAs?: string;
	server: ILexboxServer;
}
/* eslint-enable */
