version: 3
output: prefixed
tasks:
  app:
    interactive: true
    deps: [ install ]
    cmd: pnpm run dev-app
  run-app:
    interactive: true
    cmd: pnpm run dev-app
  storybook:
    interactive: true
    cmd: pnpm storybook {{.CLI_ARGS}}
  web-component:
    aliases: [ wc ]
    interactive: true
    deps: [ install ]
    cmd: pnpm run dev
  check:
    aliases: [ sc, svelte-check ]
    deps: [ install ]
    ignore_error: true
    cmds:
      - pnpm run --filter viewer check
      - pnpm run --filter viewer lint
  build-app:
    deps: [ install ]
    cmd: pnpm run build-app
  watch-app:
    deps: [ install ]
    cmd: pnpm run build-app --watch

  install:
    method: checksum
    sources:
      - package.json
      - ../pnpm-lock.yaml
      - ../pnpm-workspace.yaml
    cmds:
      - corepack enable || true
      - pnpm install
  test:
    cmd: pnpm test
  test-unit:
    cmd: pnpm test --project unit

  playwright-test:
    desc: 'runs playwright tests against already running server'
    cmd: pnpm run test:playwright {{.CLI_ARGS}}
  playwright-test-standalone:
    desc: 'runs playwright tests and runs dev-app automatically, run ui mode by calling with -- --ui or use --update-snapshots'
    env:
      AUTO_START_SERVER: true
    cmd: pnpm run test:playwright {{.CLI_ARGS}}
  generate-marketing-screenshots:
    desc: 'they should be in the screenshots folder'
    env:
      AUTO_START_SERVER: true
      MARKETING_SCREENSHOTS: true
    cmd: pnpm run test:playwright {{.CLI_ARGS}}
  playwright-test-report:
    cmd: pnpm run test:playwright-report
