version: 3
output: prefixed
tasks:
  app:
    interactive: true
    deps: [ install ]
    cmd: pnpm run dev
  run:
    interactive: true
    cmd: pnpm run dev
  storybook:
    interactive: true
    cmd: pnpm storybook {{.CLI_ARGS}}
  check:
    aliases: [ sc, svelte-check ]
    deps: [ install ]
    ignore_error: true
    cmds:
      - pnpm run --filter viewer check
      - pnpm run --filter viewer lint
  build:
    deps: [ install ]
    cmd: pnpm run build
  watch:
    deps: [ install ]
    cmd: pnpm run build --watch

  i18n:
    cmd: pnpm i18n:extract

  install:
    method: checksum
    sources:
      - package.json
      - ../pnpm-lock.yaml
      - ../pnpm-workspace.yaml
    cmds:
      - corepack enable || true
      - pnpm install
  test:
    cmd: pnpm test
  test-unit:
    cmd: pnpm test --project unit

  test:snapshot:
    desc: 'runs playwright tests against already running server'
    cmd: pnpm run test:playwright {{.CLI_ARGS}}
  test:snapshot-standalone:
    desc: 'runs playwright tests and runs dev automatically, run ui mode by calling with -- --ui or use --update-snapshots'
    env:
      AUTO_START_SERVER: true
    cmd: pnpm run test:playwright {{.CLI_ARGS}}
  generate-marketing-screenshots:
    desc: 'they should be in the screenshots folder'
    env:
      AUTO_START_SERVER: true
      MARKETING_SCREENSHOTS: true
    cmd: pnpm run test:playwright {{.CLI_ARGS}}

  test:e2e-setup:
    deps: [build]
    cmds:
      - dotnet publish ../../backend/FwLite/FwLiteWeb/FwLiteWeb.csproj --configuration Release --self-contained --output ./dist/fw-lite-server
  test:e2e:
    cmd: pnpm run test:e2e {{.CLI_ARGS}}
  e2e-test-helper-unit-tests:
    desc: 'tests the fw lite launcher, run `setup-e2e-test` first'
    cmd: pnpm test:unit --run fw-lite-launcher
