import {createRequire} from 'module';
import {defineConfig} from 'vite';

const require = createRequire(import.meta.url);
const ffmpegWorkerPath = require.resolve('@ffmpeg/ffmpeg/worker');

export default defineConfig({
  esbuild: {
    banner: `/* This file generated by Vite / pnpm build-ffmpeg-worker. */\n// @ts-nocheck`,
    include: [ffmpegWorkerPath],
  },
  build: {
    emptyOutDir: false,
    lib: {
      entry: ffmpegWorkerPath,
      formats: ['es'],
      fileName: () => 'bundled-ffmpeg-worker.js',
    },
    outDir: 'src/lib/components/audio/ffmpeg',
    copyPublicDir: false,
  },
});
