/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from Lexbox.ClientServer.Hubs.JsonOperation */
export type JsonOperation = {
    /** Transpiled from string */
    op: string;
    /** Transpiled from string */
    path: string;
    /** Transpiled from object? */
    value?: any;
    /** Transpiled from string? */
    from?: string;
}

