version: 3
output: prefixed

tasks:
  install:
    method: checksum
    sources:
      - package.json
      - package-lock.json
    cmds:
      # platform.bible does not support pnpm
      - npm install

  package:
    deps: [ build-fw-lite-web, build-viewer-component, install ]
    cmds:
      - npm run package

  run:
    deps: [ build-fw-lite-web, build-viewer-component, install ]
    cmds:
      - npm run start

  build-fw-lite-web:
    cmds:
      - dotnet publish ../../backend/FwLite/FwLiteWeb/FwLiteWeb.csproj --configuration Release --sc --output ./public/fw-lite
  build-viewer-component:
    dir: ../viewer
    cmd: pnpm run build
