version: 3
output: prefixed

tasks:
  install:
    method: checksum
    sources:
      - package.json
      - package-lock.json
    cmds:
      # platform.bible does not support pnpm
      - npm install

  package:
    deps: [ build-viewer-component, install ]
    cmds:
      - task build-local-web-app
      - npm run package

  run:
    deps: [ build-viewer-component, install ]
    cmds:
      - task build-local-web-app
      - npm run start

  build-local-web-app:
    cmds:
      - dotnet publish ../../backend/FwLite/LocalWebApp/LocalWebApp.csproj --configuration Release --sc --output ./public/fw-lite
  build-viewer-component:
    dir: ../viewer
    cmd: pnpm run build
