# https://kubernetes.io/docs/concepts/configuration/secret

apiVersion: v1
kind: Secret
metadata:
  name: db
stringData:
  POSTGRES_DB: 'lexbox'
  POSTGRES_PASSWORD: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: hasura
stringData:
  HASURA_GRAPHQL_ADMIN_SECRET: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: otel
stringData:
  HONEYCOMB_API_KEY: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: ui
stringData:
  PUBLIC_TURNSTILE_SITE_KEY: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: lexbox-api
stringData:
  Authentication__Jwt__Secret: ''
  CloudFlare__TurnstileKey: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: email
stringData:
  SMTP_USER: ''
  SMTP_PASSWORD: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
stringData:
  deploy-key: ''
