# https://taskfile.dev

version: '3'

tasks:
  api-logs:
    ignore_error: true
    cmds:
      - kubectl logs -f deployment/lexbox -c lexbox-api
  api-console:
    interactive: true
    cmds:
      - kubectl exec -it deployment/lexbox -c lexbox-api -- /bin/sh

  ui-logs:
    ignore_error: true
    cmds:
      - kubectl logs -f deployment/ui
  ui-console:
    interactive: true
    cmds:
      - kubectl exec -it deployment/ui -- /bin/sh

  infra-forward:
    interactive: true
    deps: [local-db-forward, local-otel-http-forward, local-otel-grpc-forward, local-hgweb-forward, local-resumable-forward, local-maildev-forward]
  local-db-forward:
    internal: true
    cmds:
      - kubectl port-forward service/db 5433:5432 -n languagedepot --context docker-desktop
  local-otel-http-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 4318:4318 -n languagedepot --context docker-desktop
  local-otel-grpc-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 4317:4317 -n languagedepot --context docker-desktop
  local-hgweb-forward:
    internal: true
    cmds:
      - kubectl port-forward service/hg 8088:8088 -n languagedepot --context docker-desktop
  local-resumable-forward:
    internal: true
    cmds:
      - kubectl port-forward service/hg 8034:80 -n languagedepot --context docker-desktop
  local-maildev-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 1080:1080 -n languagedepot --context docker-desktop

  local-api-forward:
    cmds:
      - kubectl port-forward service/lexbox 5158:5158 -n languagedepot --context docker-desktop

  staging-db-forward:
    cmds:
      - kubectl port-forward service/db 5434:5432 -n languagedepot --context dallas-rke


  diff-staging:
    dir: ./staging
    cmds:
      - kubectl diff -k . --context dallas-rke

  print-staging:
    dir: ./staging
    cmds:
      - kubectl kustomize .
  print-production:
    dir: ./production
    cmds:
      - kubectl kustomize .
