# https://taskfile.dev

version: '3'

tasks:
  db-up:
    cmds:
      - kubectl apply -f ./base/db-deployment.yaml
  lexbox-update:
    cmds:
      - kubectl apply -f ./lexbox-deployment.yaml
  api-logs:
    ignore_error: true
    cmds:
      - kubectl logs -f deployment/lexbox -c lexbox-api
  api-console:
    interactive: true
    cmds:
      - kubectl exec -it deployment/lexbox -c lexbox-api -- /bin/bash

  ui-logs:
    ignore_error: true
    cmds:
      - kubectl logs -f deployment/lexbox -c ui
  ui-console:
    interactive: true
    cmds:
      - kubectl exec -it deployment/lexbox -c ui -- /bin/ash


  diff-staging:
    dir: ./staging
    cmds:
      - kubectl diff -k . --context dallas-rke

  print-staging:
    dir: ./staging
    cmds:
      - kubectl kustomize .
