# https://taskfile.dev

version: '3'

tasks:
  api-logs:
    ignore_error: true
    cmds:
      - kubectl logs -f deployment/lexbox -c lexbox-api
  api-console:
    interactive: true
    cmds:
      - kubectl exec -it deployment/lexbox -c lexbox-api -- /bin/bash

  ui-logs:
    ignore_error: true
    cmds:
      - kubectl logs -f deployment/ui
  ui-console:
    interactive: true
    cmds:
      - kubectl exec -it deployment/ui -- /bin/sh

  infra-forward:
    interactive: true
    deps:
      - local-db-forward
      - local-otel-http-forward
      - local-otel-grpc-forward
      - local-hgweb-forward
      - local-resumable-forward
      - local-maildev-forward
      - local-maildev-smtp-forward
      - local-aspire-ui-forward
      - local-pgadmin-forward
  backend-forward:
    interactive: true
    deps: [infra-forward, local-api-forward]
  local-db-forward:
    cmds:
      - kubectl port-forward service/db 5433:5432 -n languagedepot --context docker-desktop
  local-otel-http-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 4318:4318 -n languagedepot --context docker-desktop
  local-otel-grpc-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 4317:4317 -n languagedepot --context docker-desktop
  local-aspire-ui-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 18888:18888 -n languagedepot --context docker-desktop
  local-hgweb-forward:
    internal: true
    cmds:
      - kubectl port-forward service/hg 8088:8088 -n languagedepot --context docker-desktop
  local-resumable-forward:
    internal: true
    cmds:
      - kubectl port-forward service/hg 8034:80 -n languagedepot --context docker-desktop
  local-maildev-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 1080:1080 -n languagedepot --context docker-desktop
  local-maildev-smtp-forward:
    internal: true
    cmds:
      - kubectl port-forward service/lexbox 1025:1025 -n languagedepot --context docker-desktop
  local-pgadmin-forward:
    internal: true
    cmds:
      - kubectl port-forward service/pgadmin 4810:80 -n languagedepot --context docker-desktop

  local-api-forward:
    cmds:
      - kubectl port-forward service/lexbox 5158:5158 -n languagedepot --context docker-desktop
  local-fw-headless-forward:
    cmds:
      - kubectl port-forward service/fw-headless 5275:8081 -n languagedepot --context docker-desktop

  staging-db-forward:
    cmds:
      - kubectl port-forward service/db 5434:5432 -n languagedepot --context dallas-stage

  develop-db-forward:
    cmds:
      - kubectl port-forward service/db 5436:5432 -n languagedepot-dev --context dallas-stage

  prod-db-forward:
    cmds:
      - kubectl port-forward service/db 5435:5432 -n languagedepot --context aws-prod
  download-sqlite-file:
    desc: 'example: `task download-sqlite-file id="<project id here>" code="<project code here>" context="dallas-stage"` the namespace can also be set'
    requires:
      vars: [id, code]
    env:
      KUBECTL_REMOTE_COMMAND_WEBSOCKETS: false
    vars:
      context: '{{.context| default "docker-desktop"}}'
      namespace: '{{.namespace| default "languagedepot"}}'
      pod:
        sh: kubectl get pods -l app=fw-headless -o jsonpath='{.items[0].metadata.name}' --context {{.context}} --namespace {{.namespace}}
    cmds:
      - kubectl cp --retries 10 {{.pod}}:/var/lib/fw-headless/projects/{{.code}}-{{.id}}/crdt.sqlite ./{{.code}}.sqlite --context {{.context}} --namespace {{.namespace}}

# Bookmarklet that generates the appropriate task on a page like: https://lexbox.org/project/sena3?id=332cc58a-76ca-466a-a447-036e02e42df7
# javascript:(function(){try{const u=new URL(window.location.href),p=u.pathname.split('/').filter(Boolean),c=p[p.length-1],i=u.searchParams.get('id');if(!i||!c){alert('Could not find project code or ID in URL');return}let ctx='docker-desktop',ns='languagedepot';const o=u.origin;if(o.includes('staging.languagedepot.org')||o.includes('lexbox.dev.languagetechnology.org'))ctx='dallas-stage';else if(o.includes('lexbox.org')||o.includes('languagedepot.org'))ctx='aws-prod';if(o.includes('lexbox.dev.languagetechnology.org'))ns='languagedepot-dev';const t=task k8s:download-fw-headless-project id="${i}" code="${c}" context="${ctx}" namespace="${ns}";navigator.clipboard.writeText(t).then(()=>alert('Copied to clipboard:\n'+t)).catch(e=>alert('Failed to copy to clipboard:\n'+e))}catch(e){alert('Error: '+e.message)}})();
  download-fw-headless-project:
    aliases: [download-project, dp]
    desc: >
      Download the entire project folder from a pod as .tar.gz and extract locally.
      Example:
      `task download-fw-headless-project id="<project id>" code="<project code>" context="dallas-stage" namespace="languagedepot"`.
    requires:
      vars: [id, code]
    vars:
      context: '{{.context | default "docker-desktop"}}'
      namespace: '{{.namespace | default "languagedepot"}}'
    cmds:
      - node download-fw-headless-project.js "{{.id}}" "{{.code}}" "{{.context}}" "{{.namespace}}"

  diff-staging:
    dir: ./staging
    cmds:
      - kubectl diff -k . --context dallas-stage

  print-staging:
    dir: ./staging
    cmds:
      - kubectl kustomize .
  print-production:
    dir: ./production
    cmds:
      - kubectl kustomize .

  check-backup-jobs:
    cmd: kubectl get jobs --context aws-prod -n languagedepot
