# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  name: fw-headless
  namespace: languagedepot
  labels:
    app: fw-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: fw-headless
  ports:
  - name: http
    protocol: TCP
    port: 80

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-headless
  namespace: languagedepot
  labels:
    app: fw-headless
spec:
  selector:
    matchLabels:
      app: fw-headless
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: fw-headless
    spec:
      securityContext:
        runAsGroup: 33
        runAsUser: 33
        runAsNonRoot: true
      containers:
      - name: fw-headless
        image: ghcr.io/sillsdev/lexbox-fw-headless:develop
        imagePullPolicy: IfNotPresent
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
        resources:
          requests:
            memory: 1500Mi
          limits:
            memory: 2400Mi
        startupProbe:
          httpGet:
            port: 80
            path: /api/healthz
          failureThreshold: 30
          periodSeconds: 10
        ports:
          - containerPort: 80

        volumeMounts:
        - name: fw-headless
          mountPath: /var/lib/fw-headless

        env:
          - name: DOTNET_URLS
            value: http://0.0.0.0:80
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: environment-name
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                  key: POSTGRES_DB
                  name: db
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db
          - name: DbConfig__LexBoxConnectionString
            value: Host=db;Port=5432;Username=postgres;Password=$(POSTGRES_PASSWORD);Database=$(POSTGRES_DB)
          - name: FwHeadlessConfig__ProjectStorageRoot
            value: /var/lib/fw-headless/projects
          - name: FwHeadlessConfig__LexboxUrl
            value: http://lexbox:5158/
          # - name: FwHeadlessConfig__HgUrl
          #   value: http://lexbox:5158/hg/
          - name: FwHeadlessConfig__LexboxUsername
            valueFrom:
              secretKeyRef:
                key: CRDT_MERGE_SEND_RECEIVE_USERNAME
                name: fw-headless
          - name: FwHeadlessConfig__LexboxPassword
            valueFrom:
              secretKeyRef:
                key: CRDT_MERGE_SEND_RECEIVE_PASSWORD
                name: fw-headless
          - name: FwHeadlessConfig__FdoDataModelVersion
            value: "7000072"

      initContainers:
      - name: populate-crdt-project-storage
        securityContext:
          # Make sure we're authorized to set ownership
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
        image: busybox:1.36.1
        command:
          - 'sh'
          - '-c'
          - |
            mkdir -p /fw-headless/projects
            chown www-data:www-data /fw-headless/projects
        volumeMounts:
          - name: fw-headless
            mountPath: /fw-headless

      volumes:
      - name: fw-headless
        persistentVolumeClaim:
          claimName: fw-headless # established in pvc.yaml
