# https://kubernetes.io/docs/concepts/configuration/secret
# excluded from kustomize so we don't overwrite values in prod/staging
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: languagedepot
stringData:
  POSTGRES_DB: 'lexbox'
  POSTGRES_PASSWORD: ''
  SEED_USER_PASSWORD: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: otel
  namespace: languagedepot
stringData:
  HONEYCOMB_API_KEY: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: ui
  namespace: languagedepot
stringData:
  PUBLIC_TURNSTILE_SITE_KEY: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: lexbox-api
  namespace: languagedepot
stringData:
  Authentication__Jwt__Secret: ''
  CloudFlare__TurnstileKey: ''
  RedmineTrustToken: ''
  LfMergeTrustToken: ''
---

apiVersion: v1
kind: Secret
metadata:
  name: email
  namespace: languagedepot
stringData:
  SMTP_USER: ''
  SMTP_PASSWORD: ''
---

apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: languagedepot
stringData:
  deploy-key: ''
