# https://kubernetes.io/docs/concepts/configuration/secret
# excluded from kustomize so we don't overwrite values in prod/staging
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: languagedepot
stringData:
  POSTGRES_DB: 'lexbox'
  POSTGRES_PASSWORD: ''
  SEED_USER_PASSWORD: ''
  QA_ADMIN_EMAIL: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: lf-mongo-auth
  namespace: languagedepot
stringData:
  MONGODB_AUTHSOURCE: ''
  MONGODB_USER: ''
  MONGODB_PASS: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: otel
  namespace: languagedepot
stringData:
  HONEYCOMB_API_KEY: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: ui
  namespace: languagedepot
stringData:
  PUBLIC_TURNSTILE_SITE_KEY: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: lexbox-api
  namespace: languagedepot
stringData:
  Authentication__Jwt__Secret: ''
  CloudFlare__TurnstileKey: ''
  LfMergeTrustToken: ''
---

apiVersion: v1
kind: Secret
metadata:
  name: email
  namespace: languagedepot
stringData:
  SMTP_USER: ''
  SMTP_PASSWORD: ''
---

apiVersion: v1
kind: Secret
metadata:
  name: google
  namespace: languagedepot
stringData:
  GOOGLE_OAUTH_CLIENT_ID: ''
  GOOGLE_OAUTH_CLIENT_SECRET: ''
---

apiVersion: v1
kind: Secret
metadata:
  name: backups
  namespace: languagedepot
stringData:
  KOPIA_PASSWORD: ''
  kopia.config: ''
---

apiVersion: v1
kind: Secret
metadata:
  name: crdtmerge
  namespace: languagedepot
stringData:
  CRDT_MERGE_SEND_RECEIVE_USERNAME: ''
  CRDT_MERGE_SEND_RECEIVE_PASSWORD: ''
