/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum UpdateResult {
	Unknown = "Unknown",
	Success = "Success",
	Failed = "Failed",
	Started = "Started",
	ManualUpdateRequired = "ManualUpdateRequired",
	Disallowed = "Disallowed"
}
/* eslint-enable */
