// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniLcm.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LcmCrdt.CompiledModels
{
    internal partial class EntryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MiniLcm.Models.Entry",
                typeof(Entry),
                baseEntityType);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Entry).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.TypeMapping = SqliteGuidTypeMapping.Default;

            var citationForm = runtimeEntityType.AddProperty(
                "CitationForm",
                typeof(MultiString),
                propertyInfo: typeof(Entry).GetProperty("CitationForm", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<CitationForm>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new LcmCrdtDbContext.MultiStringDbConverter());
            citationForm.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<MultiString>(
                    (MultiString v1, MultiString v2) => object.Equals(v1, v2),
                    (MultiString v) => v.GetHashCode(),
                    (MultiString v) => v),
                keyComparer: new ValueComparer<MultiString>(
                    (MultiString v1, MultiString v2) => object.Equals(v1, v2),
                    (MultiString v) => v.GetHashCode(),
                    (MultiString v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "jsonb"),
                converter: new ValueConverter<MultiString, string>(
                    (MultiString mul) => LcmCrdtDbContext.Serialize(mul),
                    (string json) => LcmCrdtDbContext.Deserialize<MultiString>(json) ?? new MultiString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<MultiString, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<MultiString, string>(
                        (MultiString mul) => LcmCrdtDbContext.Serialize(mul),
                        (string json) => LcmCrdtDbContext.Deserialize<MultiString>(json) ?? new MultiString())));
            citationForm.AddAnnotation("Relational:ColumnType", "jsonb");

            var complexFormTypes = runtimeEntityType.AddProperty(
                "ComplexFormTypes",
                typeof(IList<ComplexFormType>),
                propertyInfo: typeof(Entry).GetProperty("ComplexFormTypes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<ComplexFormTypes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            complexFormTypes.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<IList<ComplexFormType>>(
                    (IList<ComplexFormType> v1, IList<ComplexFormType> v2) => object.Equals(v1, v2),
                    (IList<ComplexFormType> v) => v.GetHashCode(),
                    (IList<ComplexFormType> v) => v),
                keyComparer: new ValueComparer<IList<ComplexFormType>>(
                    (IList<ComplexFormType> v1, IList<ComplexFormType> v2) => object.Equals(v1, v2),
                    (IList<ComplexFormType> v) => v.GetHashCode(),
                    (IList<ComplexFormType> v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "jsonb"),
                converter: new ValueConverter<IList<ComplexFormType>, string>(
                    (IList<ComplexFormType> list) => LcmCrdtDbContext.Serialize(list),
                    (string json) => LcmCrdtDbContext.Deserialize<List<ComplexFormType>>(json) ?? new List<ComplexFormType>()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<IList<ComplexFormType>, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<IList<ComplexFormType>, string>(
                        (IList<ComplexFormType> list) => LcmCrdtDbContext.Serialize(list),
                        (string json) => LcmCrdtDbContext.Deserialize<List<ComplexFormType>>(json) ?? new List<ComplexFormType>())));
            complexFormTypes.AddAnnotation("Relational:ColumnType", "jsonb");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(Entry).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deletedAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var lexemeForm = runtimeEntityType.AddProperty(
                "LexemeForm",
                typeof(MultiString),
                propertyInfo: typeof(Entry).GetProperty("LexemeForm", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<LexemeForm>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new LcmCrdtDbContext.MultiStringDbConverter());
            lexemeForm.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<MultiString>(
                    (MultiString v1, MultiString v2) => object.Equals(v1, v2),
                    (MultiString v) => v.GetHashCode(),
                    (MultiString v) => v),
                keyComparer: new ValueComparer<MultiString>(
                    (MultiString v1, MultiString v2) => object.Equals(v1, v2),
                    (MultiString v) => v.GetHashCode(),
                    (MultiString v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "jsonb"),
                converter: new ValueConverter<MultiString, string>(
                    (MultiString mul) => LcmCrdtDbContext.Serialize(mul),
                    (string json) => LcmCrdtDbContext.Deserialize<MultiString>(json) ?? new MultiString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<MultiString, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<MultiString, string>(
                        (MultiString mul) => LcmCrdtDbContext.Serialize(mul),
                        (string json) => LcmCrdtDbContext.Deserialize<MultiString>(json) ?? new MultiString())));
            lexemeForm.AddAnnotation("Relational:ColumnType", "jsonb");

            var literalMeaning = runtimeEntityType.AddProperty(
                "LiteralMeaning",
                typeof(RichMultiString),
                propertyInfo: typeof(Entry).GetProperty("LiteralMeaning", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<LiteralMeaning>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new LcmCrdtDbContext.RichMultiStringDbConverter());
            literalMeaning.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<RichMultiString>(
                    (RichMultiString v1, RichMultiString v2) => object.Equals(v1, v2),
                    (RichMultiString v) => v.GetHashCode(),
                    (RichMultiString v) => v),
                keyComparer: new ValueComparer<RichMultiString>(
                    (RichMultiString v1, RichMultiString v2) => object.Equals(v1, v2),
                    (RichMultiString v) => v.GetHashCode(),
                    (RichMultiString v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "jsonb"),
                converter: new ValueConverter<RichMultiString, string>(
                    (RichMultiString mul) => LcmCrdtDbContext.Serialize(mul),
                    (string json) => LcmCrdtDbContext.Deserialize<RichMultiString>(json) ?? new RichMultiString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<RichMultiString, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<RichMultiString, string>(
                        (RichMultiString mul) => LcmCrdtDbContext.Serialize(mul),
                        (string json) => LcmCrdtDbContext.Deserialize<RichMultiString>(json) ?? new RichMultiString())));
            literalMeaning.AddAnnotation("Relational:ColumnType", "jsonb");

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(RichMultiString),
                propertyInfo: typeof(Entry).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new LcmCrdtDbContext.RichMultiStringDbConverter());
            note.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<RichMultiString>(
                    (RichMultiString v1, RichMultiString v2) => object.Equals(v1, v2),
                    (RichMultiString v) => v.GetHashCode(),
                    (RichMultiString v) => v),
                keyComparer: new ValueComparer<RichMultiString>(
                    (RichMultiString v1, RichMultiString v2) => object.Equals(v1, v2),
                    (RichMultiString v) => v.GetHashCode(),
                    (RichMultiString v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "jsonb"),
                converter: new ValueConverter<RichMultiString, string>(
                    (RichMultiString mul) => LcmCrdtDbContext.Serialize(mul),
                    (string json) => LcmCrdtDbContext.Deserialize<RichMultiString>(json) ?? new RichMultiString()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<RichMultiString, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<RichMultiString, string>(
                        (RichMultiString mul) => LcmCrdtDbContext.Serialize(mul),
                        (string json) => LcmCrdtDbContext.Deserialize<RichMultiString>(json) ?? new RichMultiString())));
            note.AddAnnotation("Relational:ColumnType", "jsonb");

            var publishIn = runtimeEntityType.AddProperty(
                "PublishIn",
                typeof(List<Publication>),
                propertyInfo: typeof(Entry).GetProperty("PublishIn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entry).GetField("<PublishIn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            publishIn.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<List<Publication>>(
                    (List<Publication> v1, List<Publication> v2) => object.Equals(v1, v2),
                    (List<Publication> v) => v.GetHashCode(),
                    (List<Publication> v) => v),
                keyComparer: new ValueComparer<List<Publication>>(
                    (List<Publication> v1, List<Publication> v2) => object.Equals(v1, v2),
                    (List<Publication> v) => v.GetHashCode(),
                    (List<Publication> v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "jsonb"),
                converter: new ValueConverter<List<Publication>, string>(
                    (List<Publication> list) => LcmCrdtDbContext.Serialize(list),
                    (string json) => string.IsNullOrWhiteSpace(json) ? new List<Publication>() : LcmCrdtDbContext.Deserialize<List<Publication>>(json) ?? new List<Publication>()),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<List<Publication>, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<List<Publication>, string>(
                        (List<Publication> list) => LcmCrdtDbContext.Serialize(list),
                        (string json) => string.IsNullOrWhiteSpace(json) ? new List<Publication>() : LcmCrdtDbContext.Deserialize<List<Publication>>(json) ?? new List<Publication>())));
            publishIn.AddAnnotation("Relational:ColumnType", "jsonb");

            var snapshotId = runtimeEntityType.AddProperty(
                "SnapshotId",
                typeof(Guid?),
                nullable: true);
            snapshotId.TypeMapping = SqliteGuidTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { snapshotId },
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SnapshotId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull,
                unique: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Entry");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
