apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fw-headless
  namespace: languagedepot
  labels:
    app.kubernetes.io/part-of: languagedepot
spec:
  resources:
    requests:
      storage: 40Gi
