apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

resources:
  - ../base
patches:
  - path: lexbox-deployment.patch.yaml
  - path: app-config.yaml
  - path: hg-deployment-patch.yaml
  - path: ingress-config-staging.yaml
    target:
      kind: Ingress
      name: proxy
      namespace: languagedepot
