- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: le-langtech-cluster-issuer
- op: replace
  path: /spec/rules/0/host
  value: develop.lexbox.org
- op: replace
  path: /spec/rules/1/host
  value: hg.lexbox.dev.languagetechnology.org
- op: replace
  path: /spec/rules/2/host
  value: resumable.lexbox.dev.languagetechnology.org
- op: replace
  path: /spec/rules/3/host
  value: admin-develop.lexbox.org #not actually configured in dns, will not work
- op: replace
  path: /spec/rules/0/http/paths/2/pathType
  value: ImplementationSpecific
- op: replace
  path: /spec/rules/0/http/paths/3/pathType
  value: ImplementationSpecific
- op: replace
  path: /spec/tls/0/hosts
  value:
    - lexbox.dev.languagetechnology.org
    - hg.lexbox.dev.languagetechnology.org
    - resumable.lexbox.dev.languagetechnology.org
- op: add
  path: /spec/rules/-
  value:
    host: lexbox.dev.languagetechnology.org
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: lexbox
              port:
                name: http
        - path: /hg
          pathType: Prefix
          backend:
            service:
              name: lexbox
              port:
                name: http
        - path: /security.txt
          pathType: ImplementationSpecific
          backend:
            service:
              name: lexbox
              port:
                name: http
        - path: /.well-known
          pathType: ImplementationSpecific
          backend:
            service:
              name: lexbox
              port:
                name: http
        - path: /v1/traces
          pathType: Prefix
          backend:
            service:
              name: lexbox
              port:
                name: otel
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ui
              port:
                name: sveltekit
