- op: replace
  path: /spec/rules/0/host
  value: develop.lexbox.org
- op: replace
  path: /spec/rules/1/host
  value: hg-develop.languageforge.org
- op: replace
  path: /spec/rules/2/host
  value: resumable-develop.lexbox.org
- op: replace
  path: /spec/rules/3/host
  value: admin-develop.lexbox.org #not actually configured in dns, will not work
- op: replace
  path: /spec/tls/0/hosts
  value:
    - develop.lexbox.org
    - resumable-develop.lexbox.org
    - hg-develop.languageforge.org
