- op: replace
  path: /spec/rules/0/host
  value: staging.languagedepot.org
- op: replace
  path: /spec/rules/1/host
  value: hg-staging.languageforge.org
- op: replace
  path: /spec/rules/2/host
  value: resumable-staging.languagedepot.org
- op: replace
  path: /spec/rules/3/host
  value: admin-staging.languagedepot.org
- op: replace
  path: /spec/tls/0/hosts
  value:
    - staging.languagedepot.org
    - hg-staging.languageforge.org
    - resumable-staging.languagedepot.org
    - admin-staging.languagedepot.org
