# https://kubernetes.io/docs/concepts/configuration/secret

apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: languagedepot
stringData:
  POSTGRES_DB: 'lexbox'
  POSTGRES_PASSWORD: '972b722e63f549938d07bd8c4ee5086c'
