# https://kubernetes.io/docs/concepts/configuration/secret

apiVersion: v1
kind: Secret
metadata:
  name: hgresume
  namespace: languagedepot
stringData:
  HGRESUME_MANAGE_SECRET: '9c1f0e7a4b2d4e6f8a3b5c7d9e1f2a4b'
