# https://kubernetes.io/docs/concepts/configuration/secret

apiVersion: v1
kind: Secret
metadata:
  name: lf-mongo-auth
  namespace: languagedepot
stringData:
  MONGODB_AUTHSOURCE: 'admin'
  MONGODB_USER: 'admin'
  MONGODB_PASS: 'pass'
