  name: dotnet integration
  description: run's dotnet integration tests in a docker container for environment consistency
  inputs:
    hostname:
      description: "Target host to run the integration tests against"
      required: true
  runs:
    using: docker
    image: 'action.Dockerfile'
    args:
      - sh
      - ./.github/actions/dotnet-integration/run-tests.sh
    env:
      TEST_SERVER_HOSTNAME: ${{ inputs.hostname }}
      TEST_STANDARD_HG_HOSTNAME: hg-${{ inputs.hostname }}
      TEST_RESUMABLE_HG_HOSTNAME: resumable-${{ inputs.hostname }}
