import { LocalizeKey } from 'platform-bible-utils';

export const LOCALIZED_STRING_KEYS: LocalizeKey[] = [
  '%lexicon_addWord_buttonAdd%',
  '%lexicon_addWord_buttonSubmit%',
  '%lexicon_addWord_title%',
  '%lexicon_button_cancel%',
  '%lexicon_entryList_backToList%',
  '%lexicon_entryList_loading%',
  '%lexicon_entryList_noResults%',
  '%lexicon_entryDisplay_definition%',
  '%lexicon_entryDisplay_gloss%',
  '%lexicon_entryDisplay_headword%',
  '%lexicon_entryDisplay_partOfSpeech%',
  '%lexicon_entryDisplay_senses%',
  '%lexicon_error_failedToAddEntry%',
  '%lexicon_error_gettingNetworkObject%',
  '%lexicon_error_missingParam%',
  '%lexicon_findRelatedWord_noResultsInDomain%',
  '%lexicon_findRelatedWord_selectInstruction%',
  '%lexicon_findRelatedWord_textField%',
  '%lexicon_findWord_textField%',
  '%lexicon_selectLexicon_clear%',
  '%lexicon_selectLexicon_confirm%',
  '%lexicon_selectLexicon_loading%',
  '%lexicon_selectLexicon_noneFound%',
  '%lexicon_selectLexicon_saved%',
  '%lexicon_selectLexicon_saveError%',
  '%lexicon_selectLexicon_saving%',
  '%lexicon_selectLexicon_select%',
  '%lexicon_selectLexicon_selected%',
];
