import { LocalizeKey } from 'platform-bible-utils';

export const LOCALIZED_STRING_KEYS: LocalizeKey[] = [
  '%fwLiteExtension_addWord_buttonAdd%',
  '%fwLiteExtension_addWord_buttonSubmit%',
  '%fwLiteExtension_addWord_title%',
  '%fwLiteExtension_button_cancel%',
  '%fwLiteExtension_dictionary_backToList%',
  '%fwLiteExtension_dictionary_loading%',
  '%fwLiteExtension_dictionary_noResults%',
  '%fwLiteExtension_dictionarySelect_clear%',
  '%fwLiteExtension_dictionarySelect_confirm%',
  '%fwLiteExtension_dictionarySelect_loading%',
  '%fwLiteExtension_dictionarySelect_noneFound%',
  '%fwLiteExtension_dictionarySelect_saved%',
  '%fwLiteExtension_dictionarySelect_saveError%',
  '%fwLiteExtension_dictionarySelect_saving%',
  '%fwLiteExtension_dictionarySelect_select%',
  '%fwLiteExtension_dictionarySelect_selected%',
  '%fwLiteExtension_entryDisplay_definition%',
  '%fwLiteExtension_entryDisplay_gloss%',
  '%fwLiteExtension_entryDisplay_headword%',
  '%fwLiteExtension_entryDisplay_partOfSpeech%',
  '%fwLiteExtension_entryDisplay_senses%',
  '%fwLiteExtension_error_failedToAddEntry%',
  '%fwLiteExtension_error_gettingNetworkObject%',
  '%fwLiteExtension_error_missingParam%',
  '%fwLiteExtension_findRelatedWord_noResultsInDomain%',
  '%fwLiteExtension_findRelatedWord_selectInstruction%',
  '%fwLiteExtension_findRelatedWord_textField%',
  '%fwLiteExtension_findWord_textField%',
];
