###
# @name Email Renderer

POST http://localhost:3000/email
Content-Type: application/json

{
  "template": "ForgotPassword",
  "name": "http test",
  "resetUrl": "http://localhost:3000/reset-password?token=1234567890"
}
