apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexbox
  namespace: languagedepot
spec:
  template:
    spec:
      containers:
        - name: lexbox-api
          volumeMounts:
            - mountPath: /frontend
              name: gql-schema
      volumes:
        - name: gql-schema
          emptyDir: {}
