/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum DotnetService {
	MiniLcmApi = "MiniLcmApi",
	CombinedProjectsService = "CombinedProjectsService",
	AuthService = "AuthService",
	ImportFwdataService = "ImportFwdataService",
	FwLiteConfig = "FwLiteConfig",
	ProjectServicesProvider = "ProjectServicesProvider",
	HistoryService = "HistoryService",
	SyncService = "SyncService",
	AppLauncher = "AppLauncher",
	TroubleshootingService = "TroubleshootingService",
	TestingService = "TestingService",
	MultiWindowService = "MultiWindowService",
	JsEventListener = "JsEventListener",
	JsInvokableLogger = "JsInvokableLogger",
	UpdateService = "UpdateService"
}
/* eslint-enable */
