/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {DotnetService} from './DotnetService';

export interface IFwLiteProvider
{
	getServices() : { [key in DotnetService]: any };
	getService(service: DotnetService) : any;
}
/* eslint-enable */
