/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from '../../MiniLcm/Models/IObjectWithId';
import type {IProjectActivity} from '../../LcmCrdt/IProjectActivity';
import type {IObjectSnapshot} from '../../SIL/Harmony/Db/IObjectSnapshot';
import type {IHistoryLineItem} from '../../LcmCrdt/IHistoryLineItem';

export interface IHistoryServiceJsInvokable
{
	getObject(commitId: string, entityId: string) : Promise<IObjectWithId>;
	projectActivity() : Promise<IProjectActivity[]>;
	getSnapshot(snapshotId: string) : Promise<IObjectSnapshot>;
	getObject(timestamp: unknown, entityId: string) : Promise<IObjectWithId>;
	getHistory(entityId: string) : Promise<IHistoryLineItem[]>;
}
/* eslint-enable */
