/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IObjectWithId} from '../../MiniLcm/Models/IObjectWithId';
import type {IProjectActivity} from '../../LcmCrdt/IProjectActivity';
import type {IObjectSnapshot} from '../../SIL/Harmony/Db/IObjectSnapshot';
import type {IHistoryLineItem} from '../../LcmCrdt/IHistoryLineItem';
import type {IChangeContext} from '../../LcmCrdt/IChangeContext';

export interface IHistoryServiceJsInvokable
{
	getObject(commitId: string, entityId: string) : Promise<IObjectWithId>;
	projectActivity(skip: number, take: number) : Promise<IProjectActivity[]>;
	getSnapshot(snapshotId: string) : Promise<IObjectSnapshot>;
	getHistory(entityId: string) : Promise<IHistoryLineItem[]>;
	loadChangeContext(commitId: string, changeIndex: number) : Promise<IChangeContext>;
}
/* eslint-enable */
