/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IRemoteResource} from '../../SIL/Harmony/Resource/IRemoteResource';
import type {ILocalResource} from '../../SIL/Harmony/Resource/ILocalResource';
import type {ILcmFileMetadata} from '../../MiniLcm/Media/ILcmFileMetadata';

export interface IMediaFilesServiceJsInvokable
{
	resourcesPendingDownload() : Promise<IRemoteResource[]>;
	resourcesPendingUpload() : Promise<ILocalResource[]>;
	downloadAllResources() : Promise<void>;
	uploadAllResources() : Promise<void>;
	downloadResources(resourceIds: string[]) : Promise<void>;
	uploadResources(resourceIds: string[]) : Promise<void>;
	getFileMetadata(fileId: string) : Promise<ILcmFileMetadata>;
}
/* eslint-enable */
