/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IRemoteResource} from '../../SIL/Harmony/Resource/IRemoteResource';
import type {ILocalResource} from '../../SIL/Harmony/Resource/ILocalResource';

export interface IMediaFilesServiceJsInvokable
{
	resourcesPendingDownload() : Promise<IRemoteResource[]>;
	resourcesPendingUpload() : Promise<ILocalResource[]>;
	downloadAllResources() : Promise<void>;
	uploadAllResources() : Promise<void>;
	downloadResources(resources: IRemoteResource[]) : Promise<void>;
	uploadResources(resources: ILocalResource[]) : Promise<void>;
}
/* eslint-enable */
