/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IHarmonyResource} from '../../SIL/Harmony/Resource/IHarmonyResource';
import type {ILcmFileMetadata} from '../../MiniLcm/Media/ILcmFileMetadata';

export interface IMediaFilesServiceJsInvokable
{
	allResources() : Promise<IHarmonyResource[]>;
	downloadResources(resourceIds: string[]) : Promise<void>;
	uploadPendingResources() : Promise<void>;
	getFileMetadata(fileId: string) : Promise<ILcmFileMetadata>;
}
/* eslint-enable */
