/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {DotNet} from '@microsoft/dotnet-js-interop';

export interface IMiniLcmApiProvider
{
	getMiniLcmApi() : Promise<DotNet.DotNetObject>;
	clearMiniLcmApi() : Promise<void>;
}
/* eslint-enable */
