/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ICameraResult} from './ICameraResult';

export interface IPlatformFeaturesService
{
	supportsImageCapture() : Promise<boolean>;
	captureImage() : Promise<ICameraResult | undefined>;
	copyToClipboard(text: string) : Promise<void>;
	supportsShareFile() : Promise<boolean>;
	shareFile(file: Blob | ArrayBuffer | Uint8Array, fileName: string, contentType?: string) : Promise<void>;
	hasHardwareKeyboard() : Promise<boolean>;
}
/* eslint-enable */
