/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ICameraResult} from './ICameraResult';

export interface IPlatformFeaturesService
{
	supportsImageCapture() : Promise<boolean>;
	captureImage() : Promise<ICameraResult | undefined>;
}
/* eslint-enable */
