/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IPreferencesService
{
	get(key: string) : Promise<string | null>;
	set(key: string, value: string) : Promise<void>;
	remove(key: string) : Promise<void>;
}
/* eslint-enable */
