/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IAsyncDisposable} from '../../System/IAsyncDisposable';
import type {DotNet} from '@microsoft/dotnet-js-interop';
import type {IProjectScope} from './IProjectScope';

export interface IProjectServicesProvider extends IAsyncDisposable
{
	disposeService(service: DotNet.DotNetObject) : Promise<void>;
	tryGetCrdtProjectName(code: string) : Promise<string>;
	openCrdtProject(code: string) : Promise<IProjectScope>;
	openFwDataProject(projectName: string) : Promise<IProjectScope>;
}
/* eslint-enable */
