/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {DotNet} from '@microsoft/dotnet-js-interop';
import type {ILexboxServer} from '../Auth/ILexboxServer';
import type {IProjectData} from '../../LcmCrdt/IProjectData';

export interface IProjectScope
{
	cleanup?: DotNet.DotNetObject;
	projectName: string;
	server?: ILexboxServer;
	projectData?: IProjectData;
	miniLcm: DotNet.DotNetObject;
	historyService?: DotNet.DotNetObject;
	syncService?: DotNet.DotNetObject;
	mediaFilesService?: DotNet.DotNetObject;
}
/* eslint-enable */
