/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {ReadFileResult} from '../../MiniLcm/Models/ReadFileResult';

export interface IReadFileResponseJs
{
	stream?: {stream: () => Promise<ReadableStream>, arrayBuffer: () => Promise<ArrayBuffer>};
	fileName?: string;
	result: ReadFileResult;
	errorMessage?: string;
}
/* eslint-enable */
