/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IProjectSyncStatus} from '../../LexCore/Sync/IProjectSyncStatus';
import type {ISyncResult} from '../../LexCore/Sync/ISyncResult';
import type {ISyncResults} from '../../SIL/Harmony/ISyncResults';
import type {ILexboxServer} from '../Auth/ILexboxServer';

export interface ISyncServiceJsInvokable
{
	getSyncStatus() : Promise<IProjectSyncStatus>;
	triggerFwHeadlessSync() : Promise<ISyncResult>;
	countPendingCrdtCommits() : Promise<ISyncResult>;
	getLatestCommitDate() : Promise<string>;
	executeSync(skipNotifications: boolean) : Promise<ISyncResults>;
	getCurrentServer() : Promise<ILexboxServer>;
}
/* eslint-enable */
