/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IProjectSyncStatus} from '../../LexCore/Sync/IProjectSyncStatus';

export interface ISyncServiceJsInvokable
{
	getSyncStatus() : Promise<IProjectSyncStatus>;
}
/* eslint-enable */
