/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ITroubleshootingService
{
	canShare: boolean;
	tryOpenDataDirectory() : Promise<boolean>;
	getDataDirectory() : Promise<string>;
	openLogFile() : Promise<void>;
	shareLogFile() : Promise<void>;
	shareCrdtProject(projectCode: string) : Promise<void>;
}
/* eslint-enable */
