/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IAvailableUpdate} from '../AppUpdate/IAvailableUpdate';
import type {UpdateResult} from '../AppUpdate/UpdateResult';

export interface IUpdateService
{
	checkForUpdates() : Promise<IAvailableUpdate | null>;
	applyUpdate(update: IAvailableUpdate) : Promise<UpdateResult>;
}
/* eslint-enable */
