version: 3

tasks:
  unit:
    interactive: true
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Category!=RequiresDb&Category!=Integration&Category!=FlakyIntegration&{{.FILTER}}"

  unit-with-db:
    interactive: true
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Category!=Integration&Category!=FlakyIntegration&{{.FILTER}}"

  integration:
    interactive: true
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Category=Integration&FullyQualifiedName!~Testing.Browser&{{.FILTER}}" --results-directory ./test-results --logger trx

  flaky-integration:
    interactive: true
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Category=FlakyIntegration&FullyQualifiedName!~Testing.Browser&{{.FILTER}}" --results-directory ./test-results --logger trx

  integration-env:
    interactive: true
    dotenv: [ local.env ]
    env:
#      TEST_DEFAULT_PASSWORD: ***
      TEST_SERVER_HOSTNAME: 'staging.languagedepot.org'
      TEST_STANDARD_HG_HOSTNAME: 'hg-staging.languageforge.org'
      TEST_RESUMABLE_HG_HOSTNAME: 'resumable-staging.languagedepot.org'
    cmds:
#     - 'read -p "password: " TEST_DEFAULT_PASSWORD'
      - task integration -- {{.CLI_ARGS}}

  flaky-integration-env:
    interactive: true
    dotenv: [ local.env ]
    env:
#      TEST_DEFAULT_PASSWORD: ***
      TEST_SERVER_HOSTNAME: 'staging.languagedepot.org'
      TEST_STANDARD_HG_HOSTNAME: 'hg-staging.languageforge.org'
      TEST_RESUMABLE_HG_HOSTNAME: 'resumable-staging.languagedepot.org'
    cmds:
#     - 'read -p "password: " TEST_DEFAULT_PASSWORD'
      - task flaky-integration -- {{.CLI_ARGS}}

  # Playwright
  playwright:
    env:
#     set to enable debug mode, number of ms to delay actions
      PWDEBUG: 0
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Testing.Browser&{{.FILTER}}"

  playwright-env:
    env:
#     set to enable debug mode, number of ms to delay actions
      PWDEBUG: 0
    dotenv: [ local.env ]
    cmd: task playwright -- {{.CLI_ARGS}}

  traces:
    env:
      OUTPUT_PATH:
        sh: dotnet msbuild --getProperty:OutputPath
    cmd: explorer "{{.OUTPUT_PATH}}playwright-traces"
    ignore_error: true

  playwright-install:
    env:
      OUTPUT_PATH:
        sh: dotnet msbuild --getProperty:OutputPath
    cmd: pwsh '{{.OUTPUT_PATH}}playwright.ps1 install'
