version: 3

tasks:
  unit:
    cmds:
      - dotnet test --filter=Category!=Integration

  integration:
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Category=Integration&FullyQualifiedName!~Testing.Browser&{{.FILTER}}"

  integration-env:
    dotenv: [ local.env ]
    env:
#      TEST_DEFAULT_PASSWORD: ***
      TEST_SERVER_HOSTNAME: 'staging.languagedepot.org'
      TEST_STANDARD_HG_HOSTNAME: 'hg-staging.languageforge.org'
      TEST_RESUMABLE_HG_HOSTNAME: 'resumable-staging.languagedepot.org'
    cmds:
#     - 'read -p "password: " TEST_DEFAULT_PASSWORD'
      - task playwright -- {{.CLI_ARGS}}

  # Playwright
  playwright:
    env:
#     set to enable debug mode, number of ms to delay actions
      PWDEBUG: 0
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Testing.Browser&{{.FILTER}}"

  playwright-env:
    env:
#     set to enable debug mode, number of ms to delay actions
      PWDEBUG: 0
    dotenv: [ local.env ]
    cmd: task playwright -- {{.CLI_ARGS}}

  traces:
    cmd: explorer ".\\bin\\Debug\\net7.0\\playwright-traces"
    ignore_error: true
