version: 3

tasks:
  unit:
    cmds:
      - dotnet test --filter=Category!=Integration

  integration-staging:
    env:
      TEST_DEFAULT_PASSWORD: '***'
      TEST_SERVER_HOSTNAME: 'staging.languagedepot.org'
      TEST_STANDARD_HG_HOSTNAME: 'hg-staging.languageforge.org'
      TEST_RESUMABLE_HG_HOSTNAME: 'resumable-staging.languagedepot.org'
#      set to enable debug mode, number of ms to delay actions
      PWDEBUG: 0
    cmds:
#      - 'read -p "password: " TEST_DEFAULT_PASSWORD'
      - dotnet test --filter Category=Integration   -s ./backend/Testing/staging.runsettings

  # Playwright
  playwright:
    vars:
      FILTER: '{{default "." .CLI_ARGS}}'
    cmds:
      - dotnet test --filter="Testing.Browser&{{.FILTER}}"

  playwright-env:
    dotenv: [ local.env ]
    cmd: task playwright -- {{.CLI_ARGS}}

  traces:
    cmd: explorer ".\\bin\\Debug\\net7.0\\playwright-traces"
    ignore_error: true
