/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum FwEventType {
	EntryChanged = "EntryChanged",
	AuthenticationChanged = "AuthenticationChanged",
	ProjectEvent = "ProjectEvent",
	EntryDeleted = "EntryDeleted",
	Sync = "Sync",
	AppUpdate = "AppUpdate",
	AppUpdateProgress = "AppUpdateProgress"
}
/* eslint-enable */
