/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IFwEvent} from './IFwEvent';
import type {IFwLiteRelease} from '../../LexCore/Entities/IFwLiteRelease';
import type {FwEventType} from './FwEventType';

export interface IAppUpdateProgressEvent extends IFwEvent
{
	percentage: number;
	release: IFwLiteRelease;
	type: FwEventType;
	isGlobal: boolean;
}
/* eslint-enable */
