/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IFwEvent} from './IFwEvent';
import type {ILexboxServer} from '../Auth/ILexboxServer';
import type {FwEventType} from './FwEventType';

export interface IAuthenticationChangedEvent extends IFwEvent
{
	server: ILexboxServer;
	type: FwEventType;
	isGlobal: boolean;
}
/* eslint-enable */
