/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IFwEvent} from './IFwEvent';
import type {FwEventType} from './FwEventType';
import type {IEntry} from '../../MiniLcm/Models/IEntry';

export interface IEntryChangedEvent extends IFwEvent
{
	type: FwEventType;
	isGlobal: boolean;
	entry: IEntry;
}
/* eslint-enable */
