/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IFwEvent} from './IFwEvent';
import type {FwEventType} from './FwEventType';

export interface IJsEventListener
{
	nextEventAsync() : Promise<IFwEvent>;
	lastEvent(type: FwEventType) : Promise<IFwEvent | null>;
}
/* eslint-enable */
