/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IFwEvent} from './IFwEvent';
import type {UserNotificationType} from './UserNotificationType';
import type {UserNotificationDuration} from './UserNotificationDuration';
import type {FwEventType} from './FwEventType';

export interface IUserNotificationEvent extends IFwEvent
{
	message: string;
	description?: string;
	notificationType: UserNotificationType;
	duration: UserNotificationDuration;
	clipboardText?: string;
	type: FwEventType;
	isGlobal: boolean;
}
/* eslint-enable */
