/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum UserNotificationType {
	Plain = "Plain",
	Success = "Success",
	Error = "Error",
	Info = "Info",
	Warning = "Warning"
}
/* eslint-enable */
