/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum FwLitePlatform {
	Windows = "Windows",
	Linux = "Linux",
	Mac = "Mac",
	Other = "Other",
	Android = "Android",
	iOS = "iOS",
	Web = "Web"
}
/* eslint-enable */
