/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {FwLitePlatform} from './FwLitePlatform';

export interface IFwLiteConfig
{
	useDevAssets: boolean;
	appVersion: string;
	os: FwLitePlatform;
	feedbackUrl: string;
}
/* eslint-enable */
