/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IExemplarOptions} from './IExemplarOptions';
import type {IEntryFilter} from './Filtering/IEntryFilter';

export interface IFilterQueryOptions
{
	exemplar?: IExemplarOptions;
	filter?: IEntryFilter;
}
/* eslint-enable */
