/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {IFilterQueryOptions} from './IFilterQueryOptions';
import type {ISortOptions} from './ISortOptions';

export interface IIndexQueryOptions extends IFilterQueryOptions
{
	order: ISortOptions;
}
/* eslint-enable */
