/* eslint-disable */
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type {SortField} from './SortField';

export interface ISortOptions
{
	field: SortField;
	writingSystem: string;
	ascending: boolean;
}
/* eslint-enable */
