import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Shared by both docs instances. Everything is autogenerated from the folder
// tree, so authors order pages with `sidebar_position` frontmatter instead of
// editing this file.
const sidebars: SidebarsConfig = {
  sidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
