name: integration runner
on:
  push:
    paths:
      - '.github/workflows/dotnet-integration-runner-build.yml'
      - '.github/actions/dotnet-integration/Dockerfile'
    branches:
      - main
      - develop

jobs:
  publish-runner:
    runs-on: ubuntu-latest
    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        if: ${{ !env.ACT }}
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/sillsdev/lexbox-dotnet-integration-runner
          tags: |
            type=raw,value=latest
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .github/actions/dotnet-integration
          push: ${{ !env.ACT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
