name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      #https://github.com/actions/labeler uses .github/labeler.yml for config
      - uses: actions/labeler@v5
