name: Build lexbox UI

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  workflow_call:
    inputs:
      version:
        description: 'The version of the image to build'
        required: true
        type: string
      label-latest:
        description: 'The label to apply to the latest image'
        type: boolean
        default: false

env:
  IMAGE_NAME: ghcr.io/sillsdev/lexbox-ui

jobs:
  publish-ui:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: 'frontend/package.json'
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: './frontend/package.json'
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      - run: pnpm install
        working-directory: ./frontend
      - name: vitest
        working-directory: ./frontend
        run: |
          pnpm run test:unit --reporter=default --reporter=junit --outputFile.junit=test-results/vitest-results.xml
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          check_name: UI unit Tests
          files: ./frontend/test-results/*.xml
          action_fail_on_inconclusive: true
          comment_mode: off

      - name: Docker meta
        id: meta
        if: ${{ !env.ACT }}
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,enable=${{ inputs.label-latest }},value=latest
            type=raw,value=${{ inputs.version }}

      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: frontend
          build-args: |
            APP_VERSION=${{ inputs.version }}
          push: ${{ !env.ACT && github.repository == 'sillsdev/languageforge-lexbox' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
