name: Build FwHeadless

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  workflow_call:
    inputs:
      version:
        description: 'The version of the image to build'
        required: true
        type: string
      label-latest:
        description: 'The label to apply to the latest image'
        type: boolean
        default: false

env:
  IMAGE_NAME: ghcr.io/sillsdev/lexbox-fw-headless


jobs:
  publish-fw-headless:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    # postgres db is for automated tests
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: 972b722e63f549938d07bd8c4ee5086c
          POSTGRES_DB: lexbox-tests
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5433:5432

    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '10.x'
      - name: Dotnet build
        run: dotnet build backend/FwHeadless/FwHeadless.csproj
      - name: Unit tests
        run: dotnet test backend/Testing/Testing.csproj --logger:"xunit;LogFileName={assembly}.results.xml" --results-directory ./test-results --filter "Category!=Integration&Category!=FlakyIntegration&FullyQualifiedName~FwHeadless" --blame-hang-timeout 10m
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          check_name: C# FwHeadless Unit Tests
          files: ./test-results/*.xml
          comment_mode: off
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dotnet-fw-headless-unit-test-results
          path: ./test-results

      - name: Docker meta
        id: meta
        if: ${{ !env.ACT }}
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,enable=${{ inputs.label-latest }},value=latest
            type=raw,value=${{ inputs.version }}

      - name: ghcr.io login
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        if: ${{ !env.ACT }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: backend
          file: backend/FwHeadless/Dockerfile
          build-args: |
            APP_VERSION=${{ inputs.version }}
          push: ${{ !env.ACT && github.repository == 'sillsdev/languageforge-lexbox' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
